<?php
/**
 * Its payment method base.
 *
 * @since: 21/09/2021
 * @author: Sarwar Hasan
 * @version 1.0.0
 * @package VitePos\Libs
 */

namespace VitePos\Libs;

use Appsbd\V1\libs\AppInput;
use VitePos\Modules\POS_Settings;

/**
 * Class Payment_Swipe_Method
 *
 * @package VitePos\Libs
 */
class Payment_Woo_Methods extends Payment_Method_Base {
	/**
	 * The initialize is generated by appsbd
	 *
	 * @return mixed|void
	 */
	public function initialize() {
		$this->set_admin_name( 'woocommerce' );
		$this->admin_data->is_enable = 'N';
		$this->title = 'WC Payment';
		$this->icon  = 'vps vps-swipe-machine-2';
		$this->id    = 'B';
		$this->comp  = 'basic';
		$this->split=false;
		$this->offline=false;
		$this->set_next_handler( 'IFR', 'iframeModal' );
		add_filter( 'woocommerce_available_payment_gateways', array( $this, 'allowed_wc_payments' ),99 );
		add_filter( 'vitepos/filter/order/payment-list', array( $this, 'payment_lilst' ),10,2 );

	}

	/**
	 * The payment lilst is generated by appsbd
	 *
	 * @param mixed $payment_list It is payment_list param.
	 * @param \WC_Order $order It is order param.
	 *
	 * @return mixed
	 */
	public function payment_lilst( $payment_list,$order ) {
		foreach ( $payment_list as &$pmt ) {
			if($pmt['type']==$this->id){
				$pmt['name']=$order->get_payment_method_title().' (WC)';
			}
		}
		return $payment_list;
	}

	/**
	 * The after loaded is generated by appsbd
	 */
	public function after_loaded() {
		if(is_null($this->admin_data->settings)){
			$this->admin_data->settings['wc_allowed']=[];
		}
	}


	public function allowed_wc_payments( $available_gateways ) {
			$is_vt    = AppInput::get_value( 'vt', 'N' ) == 'Y';
			$is_kiosk = AppInput::get_value( 'is_kiosk', 'N' ) == 'Y';
			$is_user = AppInput::get_value( 'is_user', 'N' ) == 'Y';
			if ( $is_vt ) {
				if ( !$is_kiosk && !$is_user ) {
					$accepted_pms = $this->get_admin_setting( 'allowed_wc',[] );
					foreach ( $available_gateways as $gw_id => $available_gateway ) {
						if ( ! in_array( $gw_id, $accepted_pms ) ) {
							unset( $available_gateways[ $gw_id ] );
						}
					}
				}
			}

			return $available_gateways;
	}


	/**
	 * The set admin settings is generated by appsbd
	 *
	 * @return mixed|void
	 */
	public function set_admin_settings() {
		$this->set_admin_title_desc( 'Enable Woocommerce Payment', 'It will allows to take payment using woocommerce payment methods' );
		$this->set_admin_title_desc(
			'Enable %{brand} Payment',
			'It will allows to take payment using %{brand} payment methods.',
			array( 'brand' => 'Woocommerce' )
		);

		$this->set_tab_title( 'Woocomerce Payment', 'vps vps-google-wallet' );

		$wc_settings_card = $this->add_admin_card( 'wc_settings', 'Select Woocommerce Payements' );

		$wc_gateways         = WC()->payment_gateways->get_available_payment_gateways();
		$methods             = array();
		$allowed=$this->get_admin_setting("allowed_wc",[]);
		foreach ( $wc_gateways as $gateway ) {
			
			$title=!empty($gateway->settings['title'])?$gateway->settings['title']:$gateway->get_title();
			
			$item=new \stdClass();
			$item->id=$gateway->id;
			$item->val= $title;
			$item->is_selected=in_array($gateway->id,$allowed)?'Y':'N';
			$methods[]  = $item;
		}
		$wc_settings_card->add_description("Below is the list of all active WooCommerce payment gateways. Please select the payment gateways you want to use for POS.","mb-2 text-sm text-mute text-italic");
		$wc_settings_card->add_settings_field(
			"",
			'allowed_wc',
			false,
			'C',
			$methods
		);



	}

	/**
	 * The process payment is generated by appsbd
	 *
	 * @param mixed $params It is params param.
	 * @param mixed $currency_code It is currency_code param.
	 * @param mixed $order It is order param.
	 * @param mixed $outlet_id It is outlet_id param.
	 * @param mixed $counter_id It is counter_id param.
	 *
	 * @return mixed
	 */
	public function process_payment( $params, $currency_code, $order, $outlet_id, $counter_id ) {
		$params->resp->status = true;
		if ( $this->is_enable() ) {
				$params->resp->next         = 'IFR';
				$params->resp->payment_data = array(
					'payment_url'     => apply_filters('appsbd/vitepos/get-payment-url', $order->get_checkout_payment_url() . '&vt=Y',$order),
					'amount'        => $params->payment_item['amount'],
					'currency'      => $currency_code,
					'method'        => $this->id,
				);
		} else {
			$params->resp->is_delete = true;
			POS_Settings::get_module_instance()->add_error( 'Woocommerce configuration error in server' );
		}

		return $params;
	}
	public function complete_order( &$pos_payment, &$payment_list, &$payment_status_ok ) {
		foreach ( $payment_list as &$pt ) {
			if ( $this->id == $pt['type'] ) {
				if (!$pos_payment->order || !($pos_payment->order instanceof \WC_Order)) return;
				$payment_method = $pos_payment->order->get_payment_method();
				$force_methods = ['cod', 'cheque'];
				if(!empty($payment_method)) {
					if ( in_array( $payment_method, $force_methods, true ) ) {
						if ( ! $pos_payment->order->is_paid() ) {
							$pos_payment->order->payment_complete();
						}
					}
					$pt['is_paid'] = 'Y';
					$pos_payment->update_drawer();
				}
			}
		}
	}

}
