<?php
/**
 * Its used for Client Language
 *
 * @since: 21/09/2021
 * @author: Sarwar Hasan
 * @version 1.0.0
 * @package VitePos\Libs
 */

namespace VitePos\Libs;

use Vitepos\Models\Database\Mapbd_Pos_Tips_Log;

/**
 * Class WC_Stock_Manage
 *
 * @package VitePos\Libs
 */
class Tips_Log_Manage {
	/**
	 * WC_Stock_Manage constructor.
	 */
	public function __construct() {
		add_action( 'appsbd/vitepos/action/vt-order-complete', array( $this, 'add_tips_log_from_order' ), 10 );
		add_action( 'appsbd/vitepos/action/current-user-tips', array( $this, 'get_user_tips' ), 10 );
		add_action( 'appsbd/vitepos/action/user-tips-info', array( $this, 'user_tips_info' ), 10 );
		add_action( 'appsbd/vitepos/action/withdraw-user-tips', array( $this, 'add_withdraw_tips_log' ), 10, 2 );
	}

	/**
	 * The add tips log is generated by appsbd
	 *
	 * @param \WC_Order $order It is order param.
	 */
	public function add_tips_log_from_order( $order ) {
		$items   = $order->get_fees();
		$to_user = $order->get_meta( '_vtp_order_by' );
		if ( count( $items ) > 0 ) {
			foreach ( $items as $item ) {
				if ( $item->get_meta( '_vtp_custom_type' ) == 'T' ) {
					if ( ! empty( $to_user ) ) {
						$prev_amount = self::user_prev_tips( $to_user );
						$amount      = $item->get_meta( '_vtp_cal_val' ) ? $item->get_meta( '_vtp_cal_val' ) : 0;
						$in_amount   = appsbd_wc_amount( get_user_meta( $to_user, '_vtp_tips_in', true ) );
						$in_amount   += $amount;
						if ( update_user_meta( $to_user, '_vtp_tips_in', $in_amount ) ) {
							Mapbd_Pos_Tips_Log::AddLog(
								'O',
								$order->get_meta( '_vtp_outlet_id' ),
								$order->get_meta( '_vtp_cash_drawer_id' ),
								$prev_amount,
								$amount,
								$to_user,
								! empty( $order->get_customer_id() ) ? $order->get_customer_id() : '',
								$order->get_id(),
								'Order Completed'
							);
						}
					}
				}
			}
		}
	}

	/**
	 * The add tips log is generated by appsbd
	 *
	 * @param \WC_Order $order It is order param.
	 */
	public function add_withdraw_tips_log( $withdraw, $given_to ) {
		if ( ! empty( $given_to ) ) {
			$prev_amount = self::user_prev_tips( $given_to );
			$amount      = $withdraw->amount ? $withdraw->amount : 0;
			$out_amount  = appsbd_wc_amount( get_user_meta( $given_to, '_vtp_tips_out', true ) );
			$out_amount  += $amount;
			if ( update_user_meta( $given_to, '_vtp_tips_out', $out_amount ? $out_amount : 0 ) ) {
				Mapbd_Pos_Tips_Log::AddLog(
					'W',
					$withdraw->outlet_id,
					$withdraw->cashdrawer_id,
					$prev_amount,
					$amount,
					$given_to,
					get_current_user_id(),
					$withdraw->ref_val,
					'Tips Withdrawn'
				);
			}
		}
	}

	/**
	 * The get user tips is generated by appsbd
	 *
	 * @param mixed $user It is user param.
	 */
	public function get_user_tips( &$user ) {
		$user->tips = self::user_prev_tips( $user->id );
	}

	public function user_tips_info( &$user ) {
		$user->total_tips     = floatval( get_user_meta( $user->id, '_vtp_tips_in', true ) );
		$user->withdrawn_tips = floatval( get_user_meta( $user->id, '_vtp_tips_out', true ) );
	}

	/**
	 * The user reward point is generated by appsbd
	 *
	 * @param mixed  $user_id Wp User Id.
	 *
	 * @param string $type Reward type.
	 *
	 * @return float
	 */
	public static function user_prev_tips( $user_id ) {
		$prev_points = 0.0;
		if ( metadata_exists( 'user', $user_id, '_vtp_tips_in' ) ) {
			$prev_points = floatval( get_user_meta( $user_id, '_vtp_tips_in', true ) );
		}
		if ( metadata_exists( 'user', $user_id, '_vtp_tips_out' ) ) {
			$prev_points = $prev_points - floatval( get_user_meta( $user_id, '_vtp_tips_out', true ) );
		}

		return appsbd_wc_amount( $prev_points );
	}
}
