<?php
/**
 * Its used for Client Language
 *
 * @since: 21/09/2021
 * @author: Sarwar Hasan
 * @version 1.0.0
 * @package VitePos\Libs
 */

namespace VitePos\Libs;

/**
 * Class WC_Stock_Manage
 *
 * @package VitePos\Libs
 */
class WC_Stock_Manage {
	/**
	 * WC_Stock_Manage constructor.
	 */
	public function __construct() {
		add_action( 'woocommerce_reduce_order_stock', array( $this, 'order_reduce_stock' ), 10, 1 );
		add_action( 'woocommerce_restore_order_stock', array( $this, 'order_restore_stock' ), 10, 1 );
		add_filter( 'woocommerce_product_is_in_stock', array( $this, 'online_product_in_stock' ), 10, 2 );
		add_filter( 'woocommerce_product_variation_is_in_stock', array( $this, 'online_product_in_stock' ), 10, 2 );
		add_filter('woocommerce_product_variation_get_manage_stock',array($this,'get_variation_manage_stock'),10,2);
		
	}

	public function get_variation_manage_stock( $value, $product ) {
		
		file_put_contents(WP_CONTENT_DIR."/class-wc-stock-manage.txt",print_r($value,true)."\n\n",FILE_APPEND);
		if ( 'parent' === $value ) {
			return false;
		}

		
		if ( true === $value ) {
			return true;
		}

		
		return false;
	}
	/**
	 * The online product in stock is generated by appsbd
	 *
	 * @param mixed       $in_stock Its the current value.
	 * @param \WC_Product $product Its the product.
	 *
	 * @return bool
	 */
	public function online_product_in_stock( $in_stock, $product ) {
		if ( $product->get_manage_stock() && "no" == $product->get_backorders()) {
			if ( $in_stock ) {
				$quantity = $product->get_stock_quantity();
				if ( $product->get_type() != 'variable' ) {
					if ( 0 == $quantity ) {
						$in_stock = false;
						try {
							$product->set_stock_status( 'outofstock' );
							$product->save();
						} catch ( \WC_Data_Exception $e ) {
							
							return $in_stock;
						} catch ( \Exception $ex ) {
							
							return $in_stock;
						}
					}
				}
			}
		}
		return $in_stock;
	}	/**
	 * The order reduce stock is generated by appsbd
	 *
	 * @param \WC_Order $order Its order object.
	 */
	public function order_reduce_stock( $order ) {
		/**
		 * Its for check is there any change before process
		 *
		 * @since 2.0.2
		 */
		do_action( 'vitepos/action/wc-default-stock-log-add', $order, 'R' );
	}
	/**
	 * The order reduce stock is generated by appsbd
	 *
	 * @param \WC_Order $order Its order object.
	 */
	public function order_restore_stock( $order ) {
		/**
		 * Its for check is there any change before process
		 *
		 * @since 2.0.2
		 */
		do_action( 'vitepos/action/wc-default-stock-log-add', $order, 'I' );
	}
}
