<?php
/**
 * Its pos order model
 *
 * @since: 21/09/2021
 * @author: Sarwar Hasan
 * @version 1.0.0
 * @package VitePos\Libs
 */

namespace VitePos\Libs;

use Appsbd\V1\libs\AppInput;
use VitePos\Core\VitePos;
use VitePos\Modules\POS_Settings;

/**
 * Class POS_Payment
 *
 * @package VitePos\Libs
 */
class POS_Order_Payment {
	/**
	 * POS_Order_Payment constructor.
	 */
	public function __construct() {
		add_action( 'woocommerce_payment_complete', array( $this, 'order_payment_complete' ) );
		add_filter( 'woocommerce_get_checkout_order_received_url', array( $this, 'order_received_url' ), 10, 2 );
		add_filter( 'woocommerce_get_checkout_payment_url', array( $this, 'order_payment_url' ), 10, 2 );
		if ( isset( $_GET['vt'] ) && 'Y' == $_GET['vt'] ) {
			add_filter( 'woocommerce_locate_template', array( $this, 'custom_order_pay_template' ), 10, 3 );
			add_action( 'template_redirect', array( $this, 'cr_rewrite_templates' ), 1 );

			add_filter(
				'user_has_cap',
				function ( $allcaps, $caps, $args, $user ) {
					if ( ( isset( $_GET['vt'] ) ) ) {
						if ( isset( $caps[0] ) && $caps[0] === 'pay_for_order' ) {
							$order_id = $args[2] ?? 0;
							$allcaps['pay_for_order'] = true; 
						}
					}
					return $allcaps;
				},
				10,
				4
			);

			add_filter(
				'woocommerce_order_get_customer_id',
				function ( $customer_id, $order ) {
					if ( ( isset( $_GET['vt'] ) ) && ( isset( $_GET['key'] ) && $_GET['key'] === $order->get_order_key() ) ) {
						return get_current_user_id();
					}
					return $customer_id;
				},
				10,
				2
			);

			add_action(
				'woocommerce_thankyou',
				function ( $order_id ) {
					if ( ! $order_id ) {
						return;
					}
					$order = wc_get_order( $order_id );
					if ( ! $order ) {
						return;
					}

					if ( ( isset( $_GET['vt'] ) && strtoupper( $_GET['vt'] ) == 'Y' ) && ( isset( $_GET['key'] ) && $_GET['key'] === $order->get_order_key() ) ) {
						if ( ! $order->is_paid() ) {
							$order->payment_complete();
						}
					}
				}
			);
		}
	}

	/**
	 * The order payment complete is generated by appsbd
	 *
	 * @param mixed $order_id It is order_id param.
	 */
	public function order_payment_complete( $order_id ) {
			$order = wc_get_order( $order_id );
		if ( $order->get_meta( '_is_vtp_user' ) == 'Y' ) {
			$order->add_meta_data( '_vtu_paid', 'Y' );
			$order->update_meta_data( '_vt_is_paid', 'Y' );
			if ( POS_Settings::get_pos_mode() == 'P' ) {
				if ( POS_Settings::is_kitchen() ) {
					$order->update_status( 'vt_in_kitchen', 'Order Send to kitchen by user' );
				} else {
					$order->update_status( 'completed', 'Order completed by user' );
				}
			} else {
				$order->update_status( 'vtu_order_placed', '' );
			}
		} elseif ( isset( $_GET['vt'] ) && 'Y' == $_GET['vt'] ) {
			if ( $order->get_meta( '_is_vitepos' ) == 'Y' ) {
				if ( POS_Settings::get_pos_mode() == 'P' ) {
					if ( POS_Settings::is_kitchen() ) {

						$order->update_status( 'vt_in_kitchen', 'Order Send to kitchen by user' );
					} else {
						$order->update_status( 'completed', 'Order completed by user' );
					}
				} else {
					$order->update_status( 'completed', '' );
				}
			}
		}

			$order->save();
	}

	/**
	 * The order received url is generated by appsbd
	 *
	 * @param mixed     $return_url It is return_url param.
	 * @param \WC_Order $order It is order param.
	 *
	 * @return mixed|string
	 */
	public function order_received_url( $return_url, $order ) {

		
		if ( AppInput::post_value( 'vt', 'N' ) == 'Y' || $order->get_meta( '_is_vtp_user' ) == 'Y' || $order->get_meta( '_is_vitepos' ) == 'Y' ) {
			if ( strpos( $return_url, '?' ) !== false ) {
				$return_url .= '&vt=Y';
			} else {
				$return_url .= '?vt=Y';
			}
		}
		return $return_url;
	}

	/**
	 * The order received url is generated by appsbd
	 *
	 * @param mixed     $return_url It is return_url param.
	 * @param \WC_Order $order It is order param.
	 *
	 * @return mixed|string
	 */
	public function order_payment_url( $return_url, $order ) {

		
		if ( AppInput::post_value( 'vt', 'N' ) == 'Y' || $order->get_meta( '_is_vtp_user' ) == 'Y' ) {
			if ( strpos( $return_url, '?' ) !== false ) {
				$return_url .= '&vt=Y';
			} else {
				$return_url .= '?vt=Y';
			}
		}
		return $return_url;
	}

	/**
	 * The cr rewrite templates is generated by appsbd
	 *
	 * @param mixed $template It is template param.
	 */
	public function cr_rewrite_templates( $template ) {
		if ( isset( $_GET['vt'] ) && 'Y' == $_GET['vt'] ) {
			add_filter( 'show_admin_bar', '__return_false' );
			remove_all_filters( 'template_include' );
			add_filter(
				'template_include',
				function ( $template ) {
					return plugin_dir_path( VitePos::get_instance()->plugin_file ) . 'templates/order-pay-page.php';
				},
				9999
			);
		}
	}

	/**
	 * The custom order pay template is generated by appsbd
	 *
	 * @param mixed $template It is template param.
	 * @param mixed $template_name It is template_name param.
	 * @param mixed $template_path It is template_path param.
	 *
	 * @return mixed|string
	 */
	public function custom_order_pay_template( $template, $template_name, $template_path ) {
		if ( in_array( $template_name, array( 'checkout/form-pay.php', 'payment/form-pay.php' ) ) ) {
			$custom_template = plugin_dir_path( VitePos::get_instance()->plugin_file ) . 'templates/form-pay.php';

			
			if ( file_exists( $custom_template ) ) {
				return $custom_template;
			}
		}
		if ( in_array( $template_name, array( 'checkout/thankyou.php' ) ) ) {
			$custom_template = plugin_dir_path( VitePos::get_instance()->plugin_file ) . 'templates/thankyou.php';

			
			if ( file_exists( $custom_template ) ) {
				return $custom_template;
			}
		}
		return $template;
	}
}
