<?php
/**
 * Its pos order model
 *
 * @since: 21/09/2021
 * @author: Sarwar Hasan
 * @version 1.0.0
 * @package VitePos\Libs
 */

namespace vitepos\vitepos\libs;

if ( ! class_exists( __NAMESPACE__ . '\Vitepos_WC_Discounts' ) ) {
	/**
	 * Class Vitepos_Dependency
	 *
	 * @package VitePos\Libs
	 */
	class Vitepos_WC_Discounts extends \WC_Discounts {

		/**
		 * The add discounts is generated by appsbd
		 *
		 * @param mixed $code It is code param.
		 */
		public function add_discounts( $code ) {
			
		}
	}
}
