<?php
/**
 * Its payment method base.
 *
 * @since: 21/09/2021
 * @author: Sarwar Hasan
 * @version 1.0.0
 * @package VitePos\Libs
 */

namespace VitePos\Libs;

use VitePos\Api\V1\Pos_Order_Api;
use Vitepos\Models\Database\Mapbd_Pos_Counter;
use Vitepos\Models\Database\Mapbd_Pos_Warehouse;
use VitePos\Modules\POS_Settings;
use WpOrg\Requests\Exception;

/**
 * Class Payment_Stripe_Method
 *
 * @package VitePos\Libs
 */
class Payment_Wallee_Terminal_Method extends Payment_Wallee_Method {
	/**
	 * Its property secret_key
	 *
	 * @var string
	 */
	protected $secret_key = '';
	/**
	 * The initialize is generated by appsbd
	 *
	 * @return mixed|void
	 */
	public function initialize() {
		$this->set_admin_name( 'wallee_terminal' );
		$this->title = 'Wallee Terminal';
		$this->icon  = 'vps vps-wallee-w-icon';
		$this->id    = 'L';
		$this->comp  = 'basic';
		$this->allow_kiosk = true;
		$this->set_next_handler( 'WTP', 'WalleeTerminal' );
		add_filter( 'vitepos/filter/header-links', array( $this, 'prefetch_script' ), 11 );
		add_filter( 'vitepos/filter/footer-scripts', array( $this, 'footer_script' ), 9 );
		add_action( 'vitepos/action/payment/custom-process/resend-terminal', array( $this, 'resend_to_terminal' ) );
		add_action( 'vitepos/action/payment/custom-process/wallee-termeinal-pay', array( $this, 'wallee_pay' ) );
		$this->offline = false;
	}

	/**
	 * The load data is generated by appsbd
	 */
	public function load_data() {
		parent::load_data();

		

		
	}

	/**
	 * The is enable is generated by appsbd
	 *
	 * @return bool
	 */
	public function is_enable() {
		if ( 'Y' == $this->admin_data->is_enable || ! $this->admin_data->is_viewable() ) {
			if ( empty( $this->admin_data->settings ) || empty( $this->admin_data->settings['w_user_id'] ) || empty( $this->admin_data->settings['w_secret_key'] ) ) {
				return false;
			}

			return true;
		}

		return false;
	}


	/**
	 * The process payment is generated by appsbd
	 *
	 * @param mixed $params It is params param.
	 * @param mixed $currency_code It is currency_code param.
	 * @param mixed $order It is order param.
	 * @param mixed $outlet_id It is outlet_id param.
	 * @param mixed $counter_id It is counter_id param.
	 *
	 * @return mixed
	 */
	public function process_payment( $params, $currency_code, $order, $outlet_id, $counter_id ) {
		$params->resp->status = true;
		$wallee_settings = $this->admin_data;
		if ( $this->is_enable() ) {
			if ( empty( $wallee_settings->settings[ $outlet_id . '_' . $counter_id ] ) ) {
				$params->resp->is_delete = true;
				POS_Settings::get_module_instance()->add_error( 'Wallee configuration error in server' );
				return $params;
			}
			$params->resp->next         = 'WTP';
			$params->payment_item['reader_id'] = $wallee_settings->settings[ $outlet_id . '_' . $counter_id ];
			$params->resp->payment_data = array(
				'reader_id'     => $wallee_settings->settings[ $outlet_id . '_' . $counter_id ],
				'amount'        => $params->payment_item['amount'],
				'currency'      => $currency_code,
				'method'        => $this->id,
			);
		} else {
			$params->resp->is_delete = true;
			POS_Settings::get_module_instance()->add_error( 'Wallee configuration error in server' );
		}
		return $params;
	}
	/**
	 * The complete order is generated by appsbd
	 *
	 * @param POS_Payment $pos_payment Its pos_payment param.
	 * @param array       $payment_list Its payment_list param.
	 * @param bool        $payment_status_ok Its payment_status_ok param.
	 *
	 * @return mixed|void
	 */
	public function complete_order( &$pos_payment, &$payment_list, &$payment_status_ok ) {
		foreach ( $payment_list as &$pt ) {
			if ( $this->id == $pt['type'] ) {
				if ( ! empty( $pt['reader_id'] ) ) {
					$pt['is_paid'] = 'Y';
				} else {
					POS_Settings::get_module_instance()->add_error( 'Something went wrong, please cancel the order' );
					$order_details = POS_Order::get_from_woo_order_details_by_id( $pos_payment->order->get_id() );
					$pos_payment->set_order_details( false, $order_details, 'RT' );
					$payment_status_ok = false;
				}
			}
		}
	}
	/**
	 * The resend to terminal is generated by appsbd
	 *
	 * @param Pos_Order_Api $api It is api param.
	 */
	public function resend_to_terminal( &$api ) {
		$order_id = $api->get_payload( 'order_id' );
		if ( empty( $order_id ) ) {
			$api->response->set_response( false, 'Order id is missing', $api->payload );
			return;
		}
		$order        = new \WC_Order( $order_id );
		$payment_list = $order->get_meta( '_vtp_payment_list' );
		$is_found     = false;
		foreach ( $payment_list as &$payment_item ) {
			if ( $this->id == $payment_item['type'] ) {
				$is_found = true;
				break;
			}
		}
	}
	/**
	 * The get payment data is generated by appsbd
	 *
	 * @param \WC_Order $order It is order param.
	 */
	public function get_payment_data( &$order ) {
		$payment_list = $order->get_meta( '_vtp_payment_list' );
		foreach ( $payment_list as &$payment_item ) {
			if ( $this->id == $payment_item['type'] ) {
				return $payment_item;
			}
		}
		return null;
	}
	/**
	 * The cancel order is generated by appsbd
	 *
	 * @param \WC_Order $order Its order param.
	 */
	public function cancel_order( $order ) {
		if ( $order instanceof \WC_Order ) {
			$payment_list = $order->get_meta( '_vtp_payment_list' );
			$is_updated   = false;
			$cancel_transaction_no = $order->get_meta( '_vt_wtp_trans_id' );
			if ( ! empty( $cancel_transaction_no ) ) {
				foreach ( $payment_list as &$payment_item ) {
					if ( $this->id == $payment_item['type'] ) {
						if ( ! empty( $payment_item['reader_id'] ) ) {
							if ( ! empty( $this->get_admin_setting( 'w_secret_key' ) ) && ! empty( $this->get_admin_setting( 'w_user_id' ) ) ) {
								try {
									$client = new \Wallee\Sdk\ApiClient( $this->get_admin_setting( 'w_user_id' ), $this->get_admin_setting( 'w_secret_key' ) );
									$transaction = $client->getTransactionService()->read( $this->get_admin_setting( 'w_space_id' ), $cancel_transaction_no );
									try {
										$void = $client->getTransactionVoidService();
										$resvoid = $void->voidOnline( $this->get_admin_setting( 'w_space_id' ), $cancel_transaction_no );
									} catch ( \Wallee\Sdk\ApiException $e ) {
										try {
											$reObj = new \Wallee\Sdk\Model\RefundCreate();
											$reObj->setAmount( $transaction->getAuthorizationAmount() );
											$reObj->setTransaction( $cancel_transaction_no );
											$reObj->setExternalId( $transaction->getTerminal()->getExternalId() );
											$reObj->setType( \Wallee\Sdk\Model\RefundType::MERCHANT_INITIATED_ONLINE );
											$refund = $client->getRefundService()->refund( $this->get_admin_setting( 'w_space_id' ), $reObj );
										} catch ( \Wallee\Sdk\ApiException $e ) {
											$error = $e->getResponseBody();
											POS_Settings::get_module_instance()->add_error( $error->message );
										} catch ( \Wallee\Sdk\Http\ConnectionException $e ) {
											$error = $e->getResponseBody();
											POS_Settings::get_module_instance()->add_error( $error->message );
										} catch ( \Wallee\Sdk\VersioningException $e ) {
										}
									} catch ( \Wallee\Sdk\Http\ConnectionException $e ) {
										$error = $e->getResponseBody();
										POS_Settings::get_module_instance()->add_error( $error->message );
									} catch ( \Wallee\Sdk\VersioningException $e ) {
										$error = $e->getResponseBody();
										POS_Settings::get_module_instance()->add_error( $error->message );
									}
								} catch ( \Wallee\Sdk\ApiException $e ) {
									$error = $e->getResponseBody();
									POS_Settings::get_module_instance()->add_error( $error->message );
								} catch ( \Wallee\Sdk\Http\ConnectionException $e ) {
									$error = $e->getResponseBody();
									POS_Settings::get_module_instance()->add_error( $error->message );
								} catch ( \Wallee\Sdk\VersioningException $e ) {
								}
							}
							$is_updated = true;
							unset( $payment_item['reader_id'] );
							if ( isset( $payment_item['reader_id'] ) ) {
								$is_updated = true;
								unset( $payment_item['reader_id'] );
							}
						}
					}
				}
			}
			if ( $is_updated ) {
				$order->update_meta_data( '_vtp_payment_list', $payment_list );
				$order->save();
			}
		}
	}
	/**
	 * The check status is generated by appsbd
	 *
	 * @param mixed $api It is api param.
	 */
	public function wallee_pay( &$api ) {
		$order_id = $api->get_payload( 'order_id' );
		if ( empty( $order_id ) ) {
			$api->response->set_response( false, 'Order id is missing', $api->payload );
			return;
		}
		$order        = new \WC_Order( $order_id );
		$payment_data = $this->get_payment_data( $order );
		if ( empty( $payment_data['reader_id'] ) ) {
			$api->response->set_response( false, 'Need Reader Id', $payment_data );
			return;
		}
		$wallee_settings       = $this->admin_data;
		$resp_obj              = new \stdClass();
		$resp_obj->need_resend = false;
		$resp_obj->need_cancel = false;
		$resp_obj->reader      = null;
		$secret = $this->get_admin_setting( 'w_secret_key', '' );
		$user_id = $this->get_admin_setting( 'w_user_id', '' );
		$space_id = $this->get_admin_setting( 'w_space_id', '' );
		if ( ! empty( $secret ) && ! empty( $user_id ) && ! empty( $space_id ) ) {
			try {

				
				$client = new \Wallee\Sdk\ApiClient( $user_id, $secret );

				
				$lineItem = new \Wallee\Sdk\Model\LineItemCreate();
				$lineItem->setName( 'Vitepos Order Payment' );
				$lineItem->setUniqueId( $order_id );
				
				$lineItem->setQuantity( 1 );
				$amount = appsbd_wc_amount( $payment_data['amount'] );
				$lineItem->setAmountIncludingTax( $amount );
				$lineItem->setType( \Wallee\Sdk\Model\LineItemType::PRODUCT );

				$transactionPayload = new \Wallee\Sdk\Model\TransactionCreate();
				$transactionPayload->setCurrency( $order->get_currency() );
				$transactionPayload->setLineItems( array( $lineItem ) );
				$transactionPayload->setAutoConfirmationEnabled( true );

				
				$transaction = $client->getTransactionService()->create( $space_id, $transactionPayload );
				$transaction->setTerminal( $payment_data['reader_id'] );
				$transaction->getToken();
				$terminalService = $client->getPaymentTerminalTillService();
				

				$terminal_transaction = $terminalService->performTransaction( $space_id, $transaction->getId(), $payment_data['reader_id'] );
				if ( ! empty( $terminal_transaction->getId() ) ) {
					vitepos_wc_update_meta( $order->get_id(), '_vt_wtp_trans_id', $terminal_transaction->getId() );
				}

				$resp_obj->need_resend = false;
				$resp_obj->reader      = $payment_data['reader_id'];
				$api->response->set_response( true, '', $resp_obj );
			} catch ( \Wallee\Sdk\ApiException $e ) {
				$error = $e->getResponseBody();
				POS_Settings::get_module_instance()->add_error( $error->message );
				$resp_obj->need_resend = true;
				$resp_obj->reader      = $payment_data['reader_id'];
				$api->response->set_response( false, '', $resp_obj );
			} catch ( \Wallee\Sdk\Http\ConnectionException $e ) {
				$error = $e->getResponseBody();
				POS_Settings::get_module_instance()->add_error( $error->message );
				$resp_obj->need_resend = true;
				$resp_obj->reader      = $payment_data['reader_id'];
				$api->response->set_response( false, '', $resp_obj );
			} catch ( \Wallee\Sdk\VersioningException $e ) {
				$error = $e->getResponseBody();
				POS_Settings::get_module_instance()->add_error( $error->message );
				$resp_obj->need_resend = true;
				$resp_obj->reader      = $payment_data['reader_id'];
				$api->response->set_response( false, '', $resp_obj );
			}
		} else {
			POS_Settings::get_module_instance()->add_error( 'Wallee terminal server configuration error' );
			$resp_obj->need_resend = true;
			$resp_obj->reader      = $payment_data['reader_id'];
			$api->response->set_response( false, '', $resp_obj );
		}
	}

	/**
	 * The set admin settings is generated by appsbd
	 *
	 * @return mixed|void
	 */
	public function set_admin_settings() {
		parent::set_admin_settings();
		$this->set_admin_title_desc(
			'Enable %{brand} Payment',
			'It will allow you to take payment using %{brand} Payment gateway, make sure you have added %{brand} api info in %{brand} settings tab.',
			array( 'brand' => 'Wallee Terminal' )
		);
		$wallee_settings = $this->admin_data;
		if ( empty( $wallee_settings->settings['w_secret_key'] ) || empty( $wallee_settings->settings['w_user_id'] ) ) {
			
			return;
		}
		
		$wallee_settings_card = $this->add_admin_card( 'readers', 'Map With Readers' );
		$this->set_tab_title( 'Wallee Terminal', 'vps vps-wallee-w-icon' );

		$wallee_secret_key = '' . $wallee_settings->settings['w_secret_key'];
		$wallee_user_id = '' . $wallee_settings->settings['w_user_id'];
		$wallee_space_id = '' . $wallee_settings->settings['w_space_id'];
		if ( empty( $wallee_secret_key ) || empty( $wallee_user_id ) || empty( $wallee_space_id ) ) {
			$wallee_space_id = 64530;
			$wallee_user_id = 126302;
			$wallee_secret_key = 'IuHVzF6OEo3sShB6pYObSMRf4Xvbj3IMripgiZn1QEI=';
		}
		try {
			$wallee        = new \Wallee\Sdk\ApiClient( $wallee_user_id, $wallee_secret_key ); 
			$terminalService = $wallee->getPaymentTerminalService();
			$terminals = $terminalService->search( $wallee_space_id, new \Wallee\Sdk\Model\EntityQuery() );
			$readers       = array();

			$terminal      = new \stdClass();
			$terminal->id  = '';
			$terminal->val = 'Select Reader';
			$readers[]     = $terminal;

			foreach ( $terminals as $item ) {
				if ( 'ACTIVE' == $item->getState() ) {
					$terminal      = new \stdClass();
					$terminal->id  = $item->getId();
					$terminal->val = $item->getName();
					$readers[]     = $terminal;
				}
			}
			$outlets  = Mapbd_Pos_Warehouse::fetch_all_key_value( 'id', 'name' );
			$counters = Mapbd_Pos_Counter::fetch_all( '', 'outlet_id', 'ASC' );

			
			
			
			foreach ( $counters as $counter ) {
				if ( isset( $outlets[ $counter->outlet_id ] ) ) {
					$wallee_settings_card->add_settings_field(
						$outlets[ $counter->outlet_id ] . ' (' . $counter->name . ')',
						$counter->outlet_id . '_' . $counter->id,
						true,
						'W',
						$readers
					);
				}
			}
		} catch ( \Wallee\Sdk\ApiException $ex ) {
			$error = $ex->getResponseBody();
			if ( ! empty( $error->message ) ) {
				$wallee_settings_card->add_error( $error->message );
				return;
			}
			$wallee_settings_card->add_error( $ex->getMessage() );
			return;
		} catch ( \Exception $ex ) {
			$wallee_settings_card->add_error( $ex->getMessage() );
			return;
		}
	}
}
