<?php
/**
 * Its pos report library
 *
 * @since: 21/09/2021
 * @author: Sarwar Hasan
 * @version 1.0.0
 * @package VitePos\Libs
 */

namespace VitePos\Libs;

use VitePos\Modules\POS_Settings;

/**
 * Class POS_Report
 *
 * @package VitePos\Libs
 */
class POS_Report {

	/**
	 * Its property total_order
	 *
	 * @var int
	 */
	public $total_order = 0;
	/**
	 * Its property order_with_day
	 *
	 * @var array
	 */
	public $order_with_day = array();
	/**
	 * Its property order_info
	 *
	 * @var array
	 */
	public $order_info = array();
	/**
	 * Its property total_refund
	 *
	 * @var int
	 */
	public $total_refund = 0;
	/**
	 * Its property refund_with_day
	 *
	 * @var array
	 */
	public $refund_with_day = array();
	/**
	 * Its property refund_info
	 *
	 * @var array
	 */
	public $refund_info = array();
	/**
	 * Its property top_payment_method
	 *
	 * @var mixed
	 */
	public $top_payment_method;
	/**
	 * Its property payment_data
	 *
	 * @var string
	 */
	public $payment_data = array();
	/**
	 * Its property payment_method_info
	 *
	 * @var array
	 */
	public $payment_method_info = array();
	/**
	 * Its property top_product
	 *
	 * @var mixed
	 */
	public $top_product;
	/**
	 * Its property top_product_list
	 *
	 * @var string
	 */
	public $top_product_list = array();
	/**
	 * Its property top_product_info
	 *
	 * @var array
	 */
	public $top_product_info = array();
	/**
	 * Its property top_customer
	 *
	 * @var mixed
	 */
	public $top_customer;
	/**
	 * Its property top_customer_list
	 *
	 * @var string
	 */
	public $top_customer_list = array();
	/**
	 * Its property top_customer_info
	 *
	 * @var array
	 */
	public $top_customer_info = array();
	/**
	 * Its property top_staff
	 *
	 * @var mixed
	 */
	public $top_staff;
	/**
	 * Its property top_staff_list
	 *
	 * @var string
	 */
	public $top_staff_list = array();
	/**
	 * Its property top_staff_info
	 *
	 * @var array
	 */
	public $top_staff_info = array();

	/**
	 * The get order report is generated by appsbd
	 *
	 * @param array $src_props It is src_props param.
	 * @param array $sort_by_props It is sort_by_props param.
	 * @param bool  $is_order It is is_order param.
	 *
	 * @return array|\stdClass
	 */
	public static function get_order_report_bk( $src_props = array(), $sort_by_props = array(), $is_order = true ) {
		$args = array(
			'status'        => array( 'completed', $is_order ? POS_Settings::def_oder_status() : 'refunded' ),
			'orderby'       => 'date',
			'order'         => 'DESC',
			'limit'         => null,
			'paginate'      => true,
			'parent'        => $is_order ? 0 : '',
			'vt_meta_query' => array(
				array(
					'key'     => '_is_vitepos',
					'value'   => 'Y',
					'compare' => '=',
				),
			),
		);
		if ( ! $is_order ) {
			$args['vt_meta_query'][] = array(
				'key'     => '_vt_has_refund',
				'value'   => 'Y',
				'compare' => '=',
			);
		}
		if ( ! POS_Settings::is_admin_user() && ! current_user_can( 'can-see-any-outlet-orders' ) ) {
			$outlets = get_user_meta( get_current_user_id(), 'outlet_id', true );
			if ( is_array( $outlets ) ) {
				$args['vt_meta_query'][] = array(
					'key'     => '_vtp_outlet_id',
					'value'   => $outlets,
					'compare' => 'IN',
				);
			}
		}
		POS_Order::order_search_props( $args, $src_props );
		POS_Order::order_sort_param( $sort_by_props, $args );

		$orders     = wc_get_orders( $args );
		$order_data = new \stdClass();
		if ( ! empty( $orders ) ) {
			$order_list = array();
			if ( ! empty( $orders->orders ) && is_array( $orders->orders ) ) {
				foreach ( $orders->orders as $order ) {
					$pos_order_data = POS_Order::get_from_woo_order( $order );
					$order_list[]   = $pos_order_data;
				}
			}
			if ( $is_order ) {
				$order_data->total_order = count( $order_list );
			} else {
				$order_data->total_refund = count( $order_list );
			}

			$order_count_by_date = array();
			foreach ( $order_list as $order ) {
				$date = gmdate( 'F j, Y', strtotime( $order->order_date ) );
				if ( isset( $order_count_by_date[ $date ] ) ) {
					$order_count_by_date[ $date ]++;
				} else {
					$order_count_by_date[ $date ] = 1;
				}
			}

			$order_count_by_date_result = array();
			foreach ( $order_count_by_date as $date => $count ) {
				if ( $is_order ) {
					$order_count_by_date_result[] = array(
						'date'         => $date,
						'order_amount' => $count,
					);
				} else {
					$order_count_by_date_result[] = array(
						'date'          => $date,
						'refund_amount' => $count,
					);
				}
			}

			if ( $is_order ) {
				$order_data->order_with_day = $order_count_by_date_result;
			} else {
				$order_data->refund_with_day = $order_count_by_date_result;
			}
			usort(
				$order_list,
				function ( $a, $b ) {
					if ( $a->grand_total == $b->grand_total ) {
						return 0;
					}

					return ( $a->grand_total < $b->grand_total ) ? 1 : - 1;
				}
			);
			if ( $is_order ) {
				$order_data->order_info = array_slice( $order_list, 0, 5 );
			} else {
				$order_data->refund_info = array_slice( $order_list, 0, 5 );
			}
		} else {
			$order_data = null;
		}

		return $order_data;
	}

	/**
	 * The get order report is generated by appsbd
	 *
	 * @param mixed $src_props It is src_props param.
	 * @param mixed $sort_by_props It is sort_by_props param.
	 *
	 * @return array|null
	 */
	public static function get_order_report( $src_props = array(), $sort_by_props = array() ) {
		$args = array(
			'status'        => array( 'completed', POS_Settings::def_oder_status(), 'refunded' ),
			'orderby'       => 'date',
			'order'         => 'DESC',
			'limit'         => null,
			'paginate'      => true,
			'vt_meta_query' => array(
				array(
					'key'     => '_is_vitepos',
					'value'   => 'Y',
					'compare' => '=',
				),
			),
		);

		if ( ! POS_Settings::is_admin_user() && ! current_user_can( 'can-see-any-outlet-orders' ) ) {
			$outlets = get_user_meta( get_current_user_id(), 'outlet_id', true );
			if ( is_array( $outlets ) ) {
				$args['vt_meta_query'][] = array(
					'key'     => '_vtp_outlet_id',
					'value'   => $outlets,
					'compare' => 'IN',
				);
			}
		}
		POS_Order::order_search_props( $args, $src_props );
		POS_Order::order_sort_param( $sort_by_props, $args );

		$orders     = wc_get_orders( $args );
		if ( ! empty( $orders ) ) {
			$order_list = array();
			if ( ! empty( $orders->orders ) && is_array( $orders->orders ) ) {
				foreach ( $orders->orders as $order ) {
					$pos_order_data = POS_Order::get_from_woo_order( $order );
					$order_list[]   = $pos_order_data;
				}
			}
			$completed_orders = array();
			$refunded_orders  = array();
			$payment_summary  = array();
			$staff_summary    = array();
			$customer_summary = array();
			foreach ( $order_list as $order ) {

				
				if ( 'refunded' == $order->status ) {
					$refunded_orders[] = $order;
				} else {
					$completed_orders[] = $order;
				}

				
				foreach ( $order->payment_list as $payment ) {
					$type   = $payment['name'];
					$amount = $payment['amount'];
					if ( isset( $payment_summary[ $type ] ) ) {
						$payment_summary[ $type ]['total'] += $amount;
						$payment_summary[ $type ]['count'] += 1;
					} else {
						$payment_summary[ $type ]['total'] = $amount;
						$payment_summary[ $type ]['count'] = 1;
					}
				}

				
				$processed_by = $order->processed_by->name;
				if ( isset( $staff_summary[ $processed_by ] ) ) {
					$staff_summary[ $processed_by ]['total'] += $order->grand_total;
					$staff_summary[ $processed_by ]['count'] += 1;
				} else {
					$staff_summary[ $processed_by ]['total'] = $order->grand_total;
					$staff_summary[ $processed_by ]['count'] = 1;
				}

				
				if ( 'refunded' == $order->customer_id && $order->status ) {
					if ( isset( $customer_summary[ $order->customer_id ] ) ) {
						$customer_summary[ $order->customer_id ]['total'] += $order->grand_total;
					} else {
						$customer = get_user_by( 'ID', intval( $order->customer_id ) );
						if ( ! empty( $customer ) ) {
							$customer_summary[ $order->customer_id ]['name'] = $customer->first_name . ' ' . $customer->last_name;
						}
						$customer_summary[ $order->customer_id ]['total'] = $order->grand_total;
					}
				}
			}

			$completed_orders_data = self::order_info_by_status( $completed_orders );
			$refunded_orders_data  = self::order_info_by_status( $refunded_orders );
			$response              = array(
				'order'    => $completed_orders_data,
				'refund'   => $refunded_orders_data,
				'payment'  => $payment_summary,
				'staff'    => $staff_summary,
				'customer' => $customer_summary,
			);

			return $response;

		} else {
			return null;
		}
	}

	/**
	 * The order info by status is generated by appsbd
	 *
	 * @param mixed $orders It is orders param.
	 * @param mixed $is_order It is is_order param.
	 *
	 * @return \stdClass|null
	 */
	private static function order_info_by_status( $orders, $is_order = true ) {
		if ( $orders ) {
			$result = new \stdClass();
			usort(
				$orders,
				function ( $a, $b ) {
					if ( $a->grand_total == $b->grand_total ) {
						return 0;
					}

					return ( $a->grand_total < $b->grand_total ) ? 1 : - 1;
				}
			);
			$count_by_date = array();
			$counter       = 0;
			foreach ( $orders as $order ) {
				if ( $counter < 5 ) {
					$order_info = array(
						'order_id'     => $order->order_id,
						'order_c_date' => $order->order_c_date,
						'order_date'   => $order->order_date,
					);
					if ( $is_order ) {
						$order_info['grand_total'] = $order->grand_total;
					} else {
						$order_info['refund_amount'] = $order->refund_amount;
					}
					$result->info[] = $order_info;
					$counter++;
				}

				$date = gmdate( 'F j, Y', strtotime( $order->order_date ) );
				if ( isset( $count_by_date[ $date ] ) ) {
					$count_by_date[ $date ]++;
				} else {
					$count_by_date[ $date ] = 1;
				}
			}
			$count_by_date_result = array();
			foreach ( $count_by_date as $date => $count ) {
				if ( $is_order ) {
					$count_by_date_result[] = array(
						'date'         => $date,
						'order_amount' => $count,
					);
				} else {
					$count_by_date_result[] = array(
						'date'          => $date,
						'refund_amount' => $count,
					);
				}
			}
			$result->total      = count( $orders );
			$result->day_result = $count_by_date_result;

			return $result;
		} else {
			return null;
		}
	}
}
