<?php
/**
 * Vitepos Report Data
 *
 * @author: appsbd
 * @package VitePos\Libs
 */

namespace VitePos\Libs;

use Automattic\WooCommerce\Utilities\OrderUtil;
use VitePos\Core\ViteposModel;
use VitePos\Modules\POS_Settings;

/**
 * Class Vitepos_Report_Data
 *
 * @package VitePos\Libs
 */
class Vitepos_Report_Data {

	/**
	 * Its property default_status
	 *
	 * @var string
	 */
	private $default_status = null;

	/**
	 * Vitepos_Report_Data constructor.
	 */
	public function __construct() {
	}

	/**
	 * The   get is generated by appsbd
	 *
	 * @param mixed $name It is name param.
	 *
	 * @return string
	 */
	public function __get( $name ) {
		global $wpdb;

		return $wpdb->prefix . $name;
		
	}

	/**
	 * The is hpos is generated by appsbd
	 *
	 * @return bool
	 */
	public function is_hpos() {
		return OrderUtil::custom_orders_table_usage_is_enabled();
	}

	/**
	 * The get full date is generated by appsbd
	 *
	 * @param mixed $date It is date param.
	 * @param bool  $is_start It is is_start param.
	 *
	 * @return false|string
	 */
	protected function get_full_date( $date, $is_start = true ) {
		if ( $is_start ) {
			$hour = ' 00:00:00';
		} else {
			$hour = ' 23:59:59';
		}
		$date = $date . $hour;
		return $date;
	}

	/**
	 * The top customers is generated by appsbd
	 *
	 * @param mixed $outlet_id It is outlet_id param.
	 * @param mixed $start_time It is start_time param.
	 * @param mixed $end_time It is end_time param.
	 * @param mixed $name It is name param.
	 * @param mixed $email It is email param.
	 * @param mixed $limit It is limit param.
	 * @param mixed $page It is page param.
	 *
	 * @return array|object|\stdClass[]|null
	 */
	public function top_customers(
		$outlet_id,
		$start_time = null,
		$end_time = null,
		$name = null,
		$email = null,
		$limit = 10,
		$page = 0
	) {
		$date_condition  = '';
		$name_condition  = '';
		$email_condition = '';
		$offset          = 0;
		if ( ! empty( $start_time ) && ! empty( $end_time ) ) {
			$start_time = $this->get_full_date( $start_time );
			$end_time   = $this->get_full_date( $end_time, false );
			$start_time = appsbd_get_wptime_to_gmtime( $start_time, 'Y-m-d H:i:s' );
			$end_time   = appsbd_get_wptime_to_gmtime( $end_time, 'Y-m-d H:i:s' );
			if ( $this->is_hpos() ) {
				$date_condition = "AND {$this->wc_orders}.date_created_gmt BETWEEN '$start_time' AND '$end_time'";
			} else {
				$date_condition = "AND {$this->posts}.post_date_gmt BETWEEN '$start_time' AND '$end_time'";
			}
		}

		if ( ! empty( $name ) ) {
			$name           = '%' . $name . '%';
			$name_condition = "AND ({$this->users}.display_name LIKE '$name' OR {$this->users}.user_login LIKE '$name' OR fn.meta_value LIKE '$name' OR ln.meta_value Like '$name')";
		}
		if ( ! empty( $email ) ) {
			$email_condition = "AND {$this->users}.user_email = '$email'";
		}
		if ( ! empty( $page ) ) {
			$offset = ( $page - 1 ) * $limit;
		}

		if ( $this->is_hpos() ) {
			$query = "SELECT
					{$this->users}.ID as customer_id, 
					{$this->users}.display_name, 
					fn.meta_value as first_name,
					ln.meta_value as last_name,
					{$this->users}.user_email, 
					count({$this->wc_orders}.id) as total_order,
					SUM( CASE WHEN {$this->wc_orders}.status = 'wc-refunded' THEN 1 ELSE 0 END ) AS total_refund,
					sum({$this->wc_orders}.total_amount) as total_amount
				FROM
					{$this->wc_orders}
					INNER JOIN {$this->users} ON {$this->wc_orders}.customer_id = {$this->users}.ID
					INNER JOIN {$this->wc_orders_meta} AS vtp ON {$this->wc_orders}.id = vtp.order_id 
						AND vtp.meta_key = '_is_vitepos' 
						AND vtp.meta_value = 'Y'
					INNER JOIN {$this->wc_orders_meta} AS ot ON {$this->wc_orders}.id = ot.order_id 
						AND ot.meta_key = '_vtp_outlet_id' 
						AND ot.meta_value = {$outlet_id}
					LEFT JOIN {$this->usermeta} AS fn ON {$this->users}.ID = fn.user_id 
                        AND fn.meta_key = 'first_name'
                    LEFT JOIN {$this->usermeta} AS ln ON {$this->users}.ID = ln.user_id 
                        AND ln.meta_key = 'last_name'
					WHERE 1=1
					{$date_condition}
					{$email_condition}
            		{$name_condition}
					GROUP BY {$this->users}.ID
					ORDER BY 
						(COUNT({$this->wc_orders}.ID) - SUM(CASE WHEN {$this->wc_orders}.status = 'wc-refunded' THEN 1 ELSE 0 END)) DESC,
						total_order DESC,
						(SUM(CASE WHEN {$this->wc_orders}.status = 'wc-refunded' THEN 1 ELSE 0 END) / NULLIF(COUNT({$this->wc_orders}.ID), 0)) ASC
					LIMIT {$limit} OFFSET {$offset}";
		} else {
			$query = "SELECT
					{$this->users}.id AS user_id,	
					{$this->users}.display_name,
					fn.meta_value as first_name,
					ln.meta_value as last_name,
					{$this->users}.user_email,
					count({$this->posts}.ID) AS total_order,
					SUM( CASE WHEN {$this->posts}.post_status = 'wc-refunded' THEN 1 ELSE 0 END ) AS total_refund,
					sum(oam.meta_value) AS total_amount
				FROM
					{$this->posts}
				INNER JOIN {$this->postmeta} AS vtp ON {$this->posts}.ID = vtp.post_id 
					AND vtp.meta_key = '_is_vitepos' 
					AND vtp.meta_value = 'Y'
					INNER JOIN {$this->postmeta} AS oam ON {$this->posts}.ID = oam.post_id 
					AND oam.meta_key = '_order_total' 
				
				INNER JOIN {$this->postmeta} AS ot ON {$this->posts}.id = ot.post_id 
					AND ot.meta_key = '_vtp_outlet_id' 
					AND ot.meta_value = {$outlet_id}
				INNER JOIN {$this->postmeta} AS um ON {$this->posts}.id = um.post_id 
					AND um.meta_key = '_customer_user'
				INNER JOIN {$this->users} ON um.meta_value= {$this->users}.ID
				LEFT JOIN {$this->usermeta} AS fn ON {$this->users}.ID = fn.user_id 
                     AND fn.meta_key = 'first_name'
                LEFT JOIN {$this->usermeta} AS ln ON {$this->users}.ID = ln.user_id 
                     AND ln.meta_key = 'last_name'
				WHERE 1=1
				{$date_condition}
				{$email_condition}
            	{$name_condition}
				GROUP BY {$this->users}.id 
				ORDER BY 
					(COUNT({$this->posts}.ID) - SUM(CASE WHEN {$this->posts}.post_status = 'wc-refunded' THEN 1 ELSE 0 END)) DESC,
					total_order DESC,
					(SUM(CASE WHEN {$this->posts}.post_status = 'wc-refunded' THEN 1 ELSE 0 END) / NULLIF(COUNT({$this->posts}.ID), 0)) ASC
				LIMIT {$limit} OFFSET {$offset}";
		}
		$result = ViteposModel::get_db_object()->get_results( $query );
		return $result;
	}

	/**
	 * The top staffs is generated by appsbd
	 *
	 * @param mixed $outlet_id It is outlet_id param.
	 * @param mixed $start_time It is start_time param.
	 * @param mixed $end_time It is end_time param.
	 * @param mixed $limit It is limit param.
	 * @param mixed $page It is page param.
	 * @param mixed $user_id It is user_id param.
	 * @param mixed $email It is email param.
	 * @param mixed $status It is status param.
	 *
	 * @return array|object|\stdClass[]|null
	 */
	public function top_staffs(
		$outlet_id,
		$start_time,
		$end_time,
		$limit = 10,
		$page = 0,
		$user_id = null,
		$email = null,
		$status = null
	) {

		$date_condition  = '';
		$id_condition    = '';
		$email_condition = '';
		$offset          = 0;
		$this->default_status = $this->get_status( $status );

		if ( ! empty( $start_time ) && ! empty( $end_time ) ) {
			$start_time           = $this->get_full_date( $start_time );
			$end_time             = $this->get_full_date( $end_time, false );
			$start_time           = appsbd_get_wptime_to_gmtime( $start_time, 'Y-m-d H:i:s' );
			$end_time             = appsbd_get_wptime_to_gmtime( $end_time, 'Y-m-d H:i:s' );
			if ( $this->is_hpos() ) {
				$date_condition = "AND {$this->wc_orders}.date_created_gmt BETWEEN '$start_time' AND '$end_time'";
			} else {
				$date_condition = "AND {$this->posts}.post_date_gmt BETWEEN '$start_time' AND '$end_time'";
			}
		}

		if ( ! empty( $user_id ) ) {
			$id_condition = "AND {$this->users}.ID = '$user_id'";
		}
		if ( ! empty( $email ) ) {
			$email_condition = "AND {$this->users}.user_email = '$email'";
		}
		if ( ! empty( $page ) ) {
			$offset = ( $page - 1 ) * $limit;
		}

		if ( $this->is_hpos() ) {
			$query = "SELECT 
					u.meta_value AS user_id,
					fname.meta_value AS first_name,
					lname.meta_value AS last_name,
					{$this->users}.user_email,
					{$this->users}.display_name,
					{$this->users}.user_nicename ,
					{$this->usermeta}.meta_value AS contact_number,
					sum(DISTINCT {$this->wc_orders}.total_amount) AS total_amount,
					count(DISTINCT {$this->wc_orders}.id) AS total_order
				FROM
					{$this->wc_orders}
				INNER JOIN {$this->wc_orders_meta} AS vtp ON {$this->wc_orders}.id = vtp.order_id 
					AND vtp.meta_key = '_is_vitepos' 
					AND vtp.meta_value = 'Y'
				INNER JOIN {$this->wc_orders_meta} AS u ON {$this->wc_orders}.id = u.order_id 
					AND u.meta_key = '_vtp_processed_by'	
				INNER JOIN {$this->wc_orders_meta} AS ot ON {$this->wc_orders}.id = ot.order_id 
					AND ot.meta_key = '_vtp_outlet_id' 
					AND ot.meta_value = {$outlet_id}	
				INNER JOIN {$this->users} ON u.meta_value = {$this->users}.ID 
				LEFT JOIN {$this->usermeta} ON {$this->usermeta}.user_id={$this->users}.ID and {$this->usermeta}.meta_key='billing_phone'
				LEFT JOIN {$this->usermeta} AS fname ON fname.user_id={$this->users}.ID and fname.meta_key='first_name'
				LEFT JOIN {$this->usermeta} AS lname ON lname.user_id={$this->users}.ID and lname.meta_key='last_name'
	
				WHERE 1=1
				{$date_condition}
				{$id_condition}
            	{$email_condition}
				AND {$this->wc_orders}.status IN (CONCAT('wc-', '{$this->default_status}'),'wc-completed')
				GROUP BY u.meta_value
				ORDER BY total_amount DESC
				LIMIT {$limit} OFFSET {$offset}";
		} else {
			$query = "SELECT 
					um.meta_value as user_id,
					fname.meta_value as first_name,
					lname.meta_value as last_name,
					{$this->users}.user_email,
					{$this->users}.display_name,
					{$this->users}.user_nicename ,
					{$this->usermeta}.meta_value as contact_name,
					sum(oam.meta_value) as total_amount,
					count({$this->posts}.ID) as total_order
				FROM
					{$this->posts}
					INNER JOIN {$this->postmeta} AS vtp ON {$this->posts}.ID = vtp.post_id 
					AND vtp.meta_key = '_is_vitepos' 
					AND vtp.meta_value = 'Y'
					INNER JOIN {$this->postmeta} AS oam ON {$this->posts}.ID = oam.post_id 
					AND oam.meta_key = '_order_total' 
				
				INNER JOIN {$this->postmeta} AS ot ON {$this->posts}.id = ot.post_id 
					AND ot.meta_key = '_vtp_outlet_id' 
					AND ot.meta_value = {$outlet_id}
				INNER JOIN {$this->postmeta} AS um ON {$this->posts}.id = um.post_id 
				AND um.meta_key = '_vtp_processed_by'
				INNER JOIN {$this->users} ON um.meta_value = {$this->users}.ID 
				LEFT JOIN {$this->usermeta} ON {$this->usermeta}.user_id={$this->users}.ID and {$this->usermeta}.meta_key='billing_phone'
				LEFT JOIN {$this->usermeta} as fname ON fname.user_id={$this->users}.ID and fname.meta_key='first_name'
				LEFT JOIN {$this->usermeta} as lname ON lname.user_id={$this->users}.ID and lname.meta_key='last_name'
				WHERE  {$this->posts}.post_type = 'shop_order' 
				AND {$this->posts}.post_status IN (CONCAT('wc-', '{$this->default_status}'),'wc-completed')
				{$date_condition}
				{$id_condition}
            	{$email_condition}
				GROUP BY
				um.meta_value
				ORDER BY total_amount DESC
				LIMIT {$limit} OFFSET {$offset};";
		}
		return ViteposModel::get_db_object()->get_results( $query );
	}

	/**
	 * The top products is generated by appsbd
	 *
	 * @param mixed $outlet_id It is outlet_id param.
	 * @param mixed $start_time It is start_time param.
	 * @param mixed $end_time It is end_time param.
	 * @param mixed $limit It is limit param.
	 * @param mixed $status It is status param.
	 *
	 * @return array|object|\stdClass[]|null
	 */
	public function top_products( $outlet_id, $start_time, $end_time, $limit = 10, $status = null ) {
		$this->default_status = $this->get_status( $status );
		$start_time           = $this->get_full_date( $start_time );
		$end_time             = $this->get_full_date( $end_time, false );
		$start_time           = appsbd_get_wptime_to_gmtime( $start_time, 'Y-m-d H:i:s' );
		$end_time             = appsbd_get_wptime_to_gmtime( $end_time, 'Y-m-d H:i:s' );
		if ( $this->is_hpos() ) {
			$query = "SELECT
					product.id as ID,
					post_title AS product_name,
					sum( CASE WHEN ( ord.STATUS IN (CONCAT('wc-', '{$this->default_status}'),'wc-completed') AND ord.type != 'shop_order_refund' ) THEN wo_item_qty.meta_value ELSE 0 END ) AS qty,
					sum( CASE WHEN ( ord.STATUS = 'wc-refunded' OR ( ord.STATUS IN (CONCAT('wc-', '{$this->default_status}'),'wc-completed') AND ord.type = 'shop_order_refund' )) THEN IF ( wo_item_qty.meta_value > 0, wo_item_qty.meta_value, (- 1 ) * wo_item_qty.meta_value ) ELSE 0 END ) AS refund_qty 
		FROM
			{$this->posts} AS product
			INNER JOIN {$this->woocommerce_order_itemmeta} AS wo_item_id ON wo_item_id.meta_key = '_product_id' 
				AND wo_item_id.meta_value = product.ID
			INNER JOIN {$this->woocommerce_order_itemmeta} AS wo_item_qty ON wo_item_qty.order_item_id = wo_item_id.order_item_id 
				AND wo_item_qty.meta_key = '_qty'
			INNER JOIN {$this->woocommerce_order_items} AS oitem ON oitem.order_item_id = wo_item_id.order_item_id
			INNER JOIN {$this->wc_orders} AS ord ON ord.id = oitem.order_id
				AND ord.date_created_gmt BETWEEN '{$start_time}' AND '{$end_time}'
			INNER JOIN {$this->wc_orders_meta} AS vtp ON vtp.order_id = ord.id
				AND vtp.meta_key = '_is_vitepos'
				AND vtp.meta_value = 'Y'
			INNER JOIN {$this->wc_orders_meta} AS outlet ON outlet.order_id = ord.id
				AND outlet.meta_key = '_vtp_outlet_id'
				AND outlet.meta_value = {$outlet_id}
			WHERE product.post_type = 'product'
			GROUP BY product.ID
			ORDER BY qty DESC
			LIMIT 0,{$limit};";
		} else {
			$query = "SELECT
					product.ID,
					product.post_title AS product_name,
					SUM( CASE WHEN ( orders.post_status IN (CONCAT('wc-', '{$this->default_status}'),'wc-completed') AND orders.post_type != 'shop_order_refund' ) THEN wo_item_qty.meta_value ELSE 0 END ) AS qty,
					SUM(
						CASE
							WHEN ( orders.post_status = 'wc-refunded' OR ( orders.post_status IN (CONCAT('wc-', '{$this->default_status}'),'wc-completed') AND orders.post_type = 'shop_order_refund' ) ) THEN
							IF ( wo_item_qty.meta_value > 0, wo_item_qty.meta_value, (- 1 ) * wo_item_qty.meta_value )
							ELSE 0 
						END 
					) AS refund_qty 
				FROM {$this->posts} AS product
				INNER JOIN {$this->woocommerce_order_itemmeta} AS wo_item_id ON wo_item_id.meta_key = '_product_id' 
					AND wo_item_id.meta_value = product.ID
				INNER JOIN {$this->woocommerce_order_itemmeta} AS wo_item_qty ON wo_item_qty.order_item_id = wo_item_id.order_item_id 
					AND wo_item_qty.meta_key = '_qty'
				INNER JOIN {$this->woocommerce_order_items} AS oitem ON oitem.order_item_id = wo_item_id.order_item_id
				INNER JOIN {$this->posts} AS orders ON orders.ID = oitem.order_id 
					AND orders.post_date_gmt BETWEEN '{$start_time}' AND '{$end_time}'
				INNER JOIN {$this->postmeta} AS vtp ON vtp.post_id = orders.ID 
					AND vtp.meta_key = '_is_vitepos' 
					AND vtp.meta_value = 'Y'
				INNER JOIN {$this->postmeta} AS outlet ON outlet.post_id = orders.ID 
					AND outlet.meta_key = '_vtp_outlet_id' 
					AND outlet.meta_value = {$outlet_id} 
				WHERE product.post_type = 'product' 
				GROUP BY product.ID 
				ORDER BY qty DESC 
				LIMIT 0,{$limit};";
		}
		return ViteposModel::get_db_object()->get_results( $query );
	}

	/**
	 * The product list is generated by appsbd
	 *
	 * @param mixed $outlet_id It is outlet_id param.
	 * @param mixed $start_time It is start_time param.
	 * @param mixed $end_time It is end_time param.
	 * @param mixed $limit It is limit param.
	 * @param mixed $page It is page param.
	 * @param mixed $status It is status param.
	 *
	 * @return array|object|\stdClass[]|null
	 */
	public function product_list( $outlet_id, $start_time, $end_time, $limit = 20, $page = 1, $status = null ) {
		$this->default_status = $this->get_status( $status );
		$start_time           = $this->get_full_date( $start_time );
		$end_time             = $this->get_full_date( $end_time, false );
		$start_time           = appsbd_get_wptime_to_gmtime( $start_time, 'Y-m-d H:i:s' );
		$end_time             = appsbd_get_wptime_to_gmtime( $end_time, 'Y-m-d H:i:s' );
		$offset               = 0;

		$stock_type = POS_Settings::is_default_stock() ? '_stock' : '_vt_stocks';

		if ( ! empty( $page ) ) {
			$offset = ( $page - 1 ) * $limit;
		}
		if ( $this->is_hpos() ) {
			$query = "SELECT 
    				{$this->posts}.ID AS product_id,
    				{$this->posts}.post_title AS product_name,
    				price_meta.meta_value AS price,
    				SUM(
        				CASE 
            				WHEN pro_meta.meta_key IN ('_variation_id', '_product_id') 
                				AND pro_meta.meta_value = {$this->posts}.ID 
                				AND outlet.meta_key = '_vtp_outlet_id' 
                				AND outlet.meta_value = {$outlet_id} 
                				AND ot.status IN (CONCAT('wc-', '{$this->default_status}'),'wc-completed')
                				AND ot.date_created_gmt BETWEEN '{$start_time}' AND '{$end_time}'
                				THEN order_meta.meta_value 
            				ELSE 0 
        				END
    				) AS total_ordered_qty,
    				COALESCE(stock_meta.meta_value, 0) AS current_stock

					FROM {$this->posts}
					LEFT JOIN {$this->woocommerce_order_itemmeta} AS pro_meta 
    					ON (
        					(pro_meta.meta_key = '_variation_id' AND pro_meta.meta_value != 0) 
        					OR (pro_meta.meta_key = '_product_id')
    					)
    					AND {$this->posts}.ID = pro_meta.meta_value  
					LEFT JOIN {$this->woocommerce_order_items} AS order_items 
    					ON pro_meta.order_item_id = order_items.order_item_id 
    					AND order_items.order_item_type = 'line_item'
					LEFT JOIN {$this->woocommerce_order_itemmeta} AS order_meta 
    					ON order_items.order_item_id = order_meta.order_item_id 
    					AND order_meta.meta_key = '_qty'
					LEFT JOIN {$this->wc_orders_meta} AS vtp 
    					ON order_items.order_id = vtp.order_id 
    					AND vtp.meta_key = '_is_vitepos' 
    					AND vtp.meta_value = 'Y'
					LEFT JOIN {$this->wc_orders_meta} AS outlet 
    					ON order_items.order_id = outlet.order_id 
    					AND outlet.meta_key = '_vtp_outlet_id'
					LEFT JOIN {$this->wc_orders} AS ot 
    					ON order_items.order_id = ot.id 
					LEFT JOIN {$this->postmeta} AS stock_meta 
    					ON {$this->posts}.ID = stock_meta.post_id 
    					AND stock_meta.meta_key = '{$stock_type}'
					LEFT JOIN {$this->postmeta} AS price_meta 
    					ON {$this->posts}.ID = price_meta.post_id 
    					AND price_meta.meta_key = '_price'
					WHERE
					    {$this->posts}.post_status IN  ('publish','private')
					    AND (
					        ({$this->posts}.post_type = 'product' 
           	 					AND NOT EXISTS (
                					SELECT 1 
                					FROM {$this->posts} AS variations 
                					WHERE variations.post_parent = {$this->posts}.ID 
                					AND variations.post_type = 'product_variation'
            					)
       		 				)
					    )
					    OR {$this->posts}.post_type = 'product_variation'

					GROUP BY 
    					{$this->posts}.ID
					ORDER BY 
    					total_ordered_qty DESC
					LIMIT {$limit} OFFSET {$offset};";
		} else {
			$query = "SELECT 
                    {$this->posts}.ID AS product_id,
                    {$this->posts}.post_title AS product_name,
                    price_meta.meta_value AS price,
                    SUM(
                        CASE 
                            WHEN pro_meta.meta_key IN ('_variation_id', '_product_id') 
                                AND pro_meta.meta_value = {$this->posts}.ID 
                                AND outlet.meta_key = '_vtp_outlet_id' 
                                AND outlet.meta_value = {$outlet_id} 
                                AND ot.post_status IN (CONCAT('wc-', '{$this->default_status}'),'wc-completed')
                                AND ot.post_date_gmt BETWEEN '{$start_time}' AND '{$end_time}'
                            THEN order_meta.meta_value 
                            ELSE 0 
                        END
                    ) AS total_ordered_qty,
                    stock_meta.meta_value AS current_stock
				FROM {$this->posts}
				LEFT JOIN {$this->woocommerce_order_itemmeta} AS pro_meta ON ( (pro_meta.meta_key = '_variation_id' AND pro_meta.meta_value != 0) OR (pro_meta.meta_key = '_product_id'))
				    AND {$this->posts}.ID = pro_meta.meta_value  
				LEFT JOIN {$this->woocommerce_order_items} AS order_items ON pro_meta.order_item_id = order_items.order_item_id 
                    AND order_items.order_item_type = 'line_item'
				LEFT JOIN  {$this->woocommerce_order_itemmeta} AS order_meta ON order_items.order_item_id = order_meta.order_item_id 
                    AND order_meta.meta_key = '_qty'
				LEFT JOIN {$this->postmeta} AS vtp ON order_items.order_id = vtp.post_id 
                    AND vtp.meta_key = '_is_vitepos' 
                    AND vtp.meta_value = 'Y'
				LEFT JOIN {$this->postmeta} AS outlet ON order_items.order_id = outlet.post_id 
                    AND outlet.meta_key = '_vtp_outlet_id'
				LEFT JOIN {$this->posts} AS ot ON order_items.order_id = ot.ID 
                    AND ot.post_type = 'shop_order'
				LEFT JOIN {$this->postmeta} AS stock_meta ON {$this->posts}.ID = stock_meta.post_id 
                    AND stock_meta.meta_key = '{$stock_type}'
				LEFT JOIN {$this->postmeta} AS price_meta ON {$this->posts}.ID = price_meta.post_id 
                    AND price_meta.meta_key = '_price'
				WHERE {$this->posts}.post_status IN  ('publish','private')
                    AND (
                            ({$this->posts}.post_type = 'product' 
                                AND NOT EXISTS (
                                    SELECT 1  FROM {$this->posts} AS variations 
                                         WHERE variations.post_parent = {$this->posts}.ID 
                                         AND variations.post_type = 'product_variation'
                                )
                            )
                            OR {$this->posts}.post_type = 'product_variation'
                    )
				GROUP BY {$this->posts}.ID
				ORDER BY total_ordered_qty DESC
				LIMIT {$limit} OFFSET {$offset}";
		}

		$results = ViteposModel::get_db_object()->get_results( $query );
		if ( ! POS_Settings::is_default_stock() ) {
			foreach ( $results as &$result ) {
				if ( ! empty( $result->current_stock ) ) {
					$result->current_stock = unserialize( $result->current_stock );
					if ( array_key_exists( $outlet_id, $result->current_stock ) ) {
						$result->current_stock = $result->current_stock[ $outlet_id ];
					} else {
						$result->current_stock = 0;
					}
				}
			}
		}

		return $results;
	}


	/**
	 * The search product is generated by appsbd
	 *
	 * @param mixed $product_id It is product_id param.
	 *
	 * @return array|object|\stdClass[]|null
	 */
	public function search_product( $product_id ) {
		if ( $this->is_hpos() ) {
			$query = "SELECT
						all_outlets.outlet_id AS outlet_id,
						COALESCE ( SUM( CASE WHEN outlet.meta_value = all_outlets.outlet_id THEN order_meta.meta_value ELSE 0 END ), 0 ) AS total_ordered_qty 
					  FROM
						( SELECT DISTINCT meta_value AS outlet_id FROM {$this->wc_orders_meta} WHERE meta_key = '_vtp_outlet_id' ) AS all_outlets
						LEFT JOIN {$this->woocommerce_order_itemmeta} AS pro_meta ON ( ( pro_meta.meta_key = '_variation_id' AND pro_meta.meta_value != 0 ) OR ( pro_meta.meta_key = '_product_id' ) )
						LEFT JOIN {$this->woocommerce_order_items} AS order_items ON pro_meta.order_item_id = order_items.order_item_id 
							AND order_items.order_item_type = 'line_item'
						LEFT JOIN {$this->woocommerce_order_itemmeta} AS order_meta ON order_items.order_item_id = order_meta.order_item_id 
							AND order_meta.meta_key = '_qty'
						LEFT JOIN {$this->wc_orders_meta} AS outlet ON order_items.order_id = outlet.order_id 
							AND outlet.meta_key = '_vtp_outlet_id'
						LEFT JOIN {$this->wc_orders_meta} AS vtp ON order_items.order_id = vtp.order_id 
							AND vtp.meta_key = '_is_vitepos' 
							AND vtp.meta_value = 'Y'
						LEFT JOIN {$this->posts} ON {$this->posts}.ID = pro_meta.meta_value 
						WHERE
							{$this->posts}.post_status = 'publish' 
						AND (
						        (
						            {$this->posts}.post_type = 'product' AND NOT EXISTS ( SELECT 1 FROM {$this->posts} AS variations WHERE variations.post_parent = {$this->posts}.ID AND variations.post_type = 'product_variation' ) 
                                ) 
								OR {$this->posts}.post_type = 'product_variation' 
							) 
						AND {$this->posts}.ID = {$product_id}
					  GROUP BY all_outlets.outlet_id 
					  ORDER BY all_outlets.outlet_id;	
					  ";
		} else {
			$query = "SELECT
						all_outlets.outlet_id AS outlet_id,
						COALESCE ( SUM( CASE WHEN outlet.meta_value = all_outlets.outlet_id THEN order_meta.meta_value ELSE 0 END ), 0 ) AS total_ordered_qty 
					FROM ( SELECT DISTINCT meta_value AS outlet_id FROM {$this->postmeta} WHERE meta_key = '_vtp_outlet_id' ) AS all_outlets
						LEFT JOIN {$this->woocommerce_order_itemmeta} AS pro_meta ON ( pro_meta.meta_key = '_variation_id' AND pro_meta.meta_value != 0 ) 
							OR ( pro_meta.meta_key = '_product_id' )
						LEFT JOIN {$this->woocommerce_order_items} AS order_items ON pro_meta.order_item_id = order_items.order_item_id 
							AND order_items.order_item_type = 'line_item'
						LEFT JOIN {$this->woocommerce_order_itemmeta} AS order_meta ON order_items.order_item_id = order_meta.order_item_id 
							AND order_meta.meta_key = '_qty'
						LEFT JOIN {$this->postmeta} AS outlet ON order_items.order_id = outlet.post_id 
							AND outlet.meta_key = '_vtp_outlet_id'
						LEFT JOIN {$this->postmeta} AS vtp ON order_items.order_id = vtp.post_id 
							AND vtp.meta_key = '_is_vitepos' 
							AND vtp.meta_value = 'Y'
						LEFT JOIN {$this->posts} ON {$this->posts}.ID = pro_meta.meta_value 
					WHERE {$this->posts}.post_status = 'publish' 
						AND (
								( {$this->posts}.post_type = 'product' 
									AND NOT EXISTS ( SELECT 1 FROM {$this->posts} AS variations WHERE variations.post_parent = {$this->posts}.ID AND variations.post_type = 'product_variation' )
								) 
								OR {$this->posts}.post_type = 'product_variation' 
							) 
						AND {$this->posts}.ID = {$product_id}
					GROUP BY all_outlets.outlet_id 
					ORDER BY all_outlets.outlet_id;";
		}

		return ViteposModel::get_db_object()->get_results( $query );
	}


	/**
	 * The payment methods report is generated by appsbd
	 *
	 * @param mixed $outlet_id It is outlet_id param.
	 * @param mixed $start_time It is start_time param.
	 * @param mixed $end_time It is end_time param.
	 * @param int   $limit It is limit param.
	 *
	 * @return array|object|\stdClass[]|null
	 */
	public function payment_methods_report( $outlet_id, $start_time, $end_time, $limit = 10 ) {
		$start_time = $this->get_full_date( $start_time );
		$end_time   = $this->get_full_date( $end_time, false );

		$query          = "SELECT
					{$this->apbd_pos_cash_drawer_types}.payment_type, 
					SUM({$this->apbd_pos_cash_drawer_types}.amount) AS amount,	
					COUNT({$this->apbd_pos_cash_drawer_types}.payment_type) AS order_count
				FROM {$this->apbd_pos_cash_drawer_types}
				INNER JOIN {$this->apbd_pos_cash_drawer} ON {$this->apbd_pos_cash_drawer_types}.cash_drawer_id = {$this->apbd_pos_cash_drawer}.id	
					AND {$this->apbd_pos_cash_drawer}.outlet_id = {$outlet_id}
				WHERE {$this->apbd_pos_cash_drawer_types}.payment_type != '_' 
				AND {$this->apbd_pos_cash_drawer_types}.entry_time BETWEEN  '{$start_time}' and '{$end_time}'
				GROUP BY payment_type
				ORDER BY amount DESC;";
		$data           = ViteposModel::get_db_object()->get_results( $query );
		$methods        = \VitePos\Modules\POS_Payment::get_payment_methods( '', true );
		$method_key_val = array();
		foreach ( $methods as $method ) {
			$method_key_val[ $method->id ] = \VitePos\Modules\POS_Payment::get_module_instance()->payment_name_by_id(
				$method->title,
				$method->id
			);
		}
		$data_arr = array();
		foreach ( $data as $key => &$payment ) {
			if ( 'R' === $payment->payment_type ) {
				unset( $data[ $key ] );
			} else {
				$payment->title = appsbd_get_text_by_key( $payment->payment_type, $method_key_val );
				$data_arr[]     = $payment;
			}
		}

		return $data_arr;
	}

	/**
	 * The day wise order is generated by appsbd
	 *
	 * @param mixed $outlet_id It is outlet_id param.
	 * @param mixed $start_time It is start_time param.
	 * @param mixed $end_time It is end_time param.
	 * @param mixed $status It is status param.
	 *
	 * @return array|object|\stdClass[]|null
	 */
	public function day_wise_order( $outlet_id, $start_time, $end_time, $status = null ) {
		$this->default_status = $this->get_status( $status );
		$start_time           = $this->get_full_date( $start_time );
		$end_time             = $this->get_full_date( $end_time, false );

		if ( $this->is_hpos() ) {
			$query = "SELECT
	 				DATE(date_created_gmt) AS order_date,
	 				SUM(CASE WHEN {$this->wc_orders}.status IN (CONCAT('wc-', '{$this->default_status}'),'wc-completed') THEN 1 ELSE 0 END) AS completed_orders,
	 				SUM(CASE WHEN {$this->wc_orders}.status = 'wc-refunded' THEN 1 ELSE 0 END) AS refund_orders,
	 				SUM(COALESCE(om.total_tax, 0)) AS total_tax
				FROM {$this->wc_orders}
 				INNER JOIN {$this->wc_orders_meta} AS vtp ON {$this->wc_orders}.id = vtp.order_id 
					AND vtp.meta_key = '_is_vitepos' 
					AND vtp.meta_value = 'Y'
				INNER JOIN {$this->wc_orders_meta} AS ot ON {$this->wc_orders}.id = ot.order_id 
					AND ot.meta_key = '_vtp_outlet_id' 
					AND ot.meta_value = {$outlet_id}
 				LEFT JOIN ( SELECT order_id, SUM(total_tax) AS total_tax
    						FROM {$this->wc_order_tax_lookup}
    						GROUP BY order_id) AS om ON {$this->wc_orders}.id = om.order_id
				WHERE {$this->wc_orders}.date_created_gmt BETWEEN  '{$start_time}' AND '{$end_time}'
				GROUP BY order_date";
		} else {
			$query = "SELECT
					DATE( {$this->posts}.post_date_gmt ) AS order_date,
					SUM( CASE WHEN {$this->posts}.post_status IN (CONCAT('wc-', '{$this->default_status}'),'wc-completed') THEN 1 ELSE 0 END ) AS completed_orders,
					SUM( CASE WHEN {$this->posts}.post_status = 'wc-refunded' THEN 1 ELSE 0 END ) AS refund_orders,
				    SUM( CASE WHEN op.meta_value IS NOT NULL THEN op.meta_value ELSE 0 END) AS total_tax
				FROM {$this->posts}
				INNER JOIN {$this->postmeta} AS vtp ON {$this->posts}.ID = vtp.post_id 
					AND vtp.meta_key = '_is_vitepos' 
					AND vtp.meta_value = 'Y'
				INNER JOIN {$this->postmeta} AS ot ON {$this->posts}.ID = ot.post_id 
					AND ot.meta_key = '_vtp_outlet_id' 
					AND ot.meta_value = {$outlet_id}
				LEFT JOIN {$this->postmeta} AS op ON {$this->posts}.ID = op.post_id 
    				AND op.meta_key = '_order_tax'                        
				WHERE {$this->posts}.post_type = 'shop_order' 
					AND {$this->posts}.post_date_gmt BETWEEN '{$start_time}' AND '{$end_time}'
				GROUP BY order_date";
		}


		return ViteposModel::get_db_object()->get_results( $query );
	}

	/**
	 * The top orders is generated by appsbd
	 *
	 * @param mixed $outlet_id It is outlet_id param.
	 * @param mixed $start_time It is start_time param.
	 * @param mixed $end_time It is end_time param.
	 * @param mixed $status It is status param.
	 * @param mixed $limit It is limit param.
	 *
	 * @return array|object|\stdClass[]|null
	 */
	public function top_orders( $outlet_id, $start_time, $end_time, $status, $limit = 10 ) {
		$start_time = $this->get_full_date( $start_time );
		$end_time   = $this->get_full_date( $end_time, false );
		if ( $this->is_hpos() ) {
			$query = "SELECT
	 				DATE(date_created_gmt) AS order_date,
	 				{$this->wc_orders}.id as order_id,
	 				{$this->wc_orders}.total_amount as order_amount
				FROM {$this->wc_orders}
 				INNER JOIN {$this->wc_orders_meta} AS vtp ON {$this->wc_orders}.id = vtp.order_id 
					AND vtp.meta_key = '_is_vitepos' 
					AND vtp.meta_value = 'Y'
				INNER JOIN {$this->wc_orders_meta} AS ot ON {$this->wc_orders}.id = ot.order_id 
					AND ot.meta_key = '_vtp_outlet_id' 
					AND ot.meta_value = {$outlet_id}
				WHERE {$this->wc_orders}.date_created_gmt BETWEEN  '{$start_time}' AND '{$end_time}'
					AND {$this->wc_orders}.status = '{$status}'
				ORDER BY order_date DESC
				LIMIT {$limit}";
		} else {
			$query = "SELECT
                    DATE({$this->posts}.post_date_gmt) AS order_date,
                    {$this->posts}.ID AS order_id,
                   oam.meta_value AS order_amount
				FROM {$this->posts}
				INNER JOIN {$this->postmeta} AS vtp ON {$this->posts}.ID = vtp.post_id 
                    AND vtp.meta_key = '_is_vitepos' 
                    AND vtp.meta_value = 'Y'
				INNER JOIN {$this->postmeta} AS ot ON {$this->posts}.ID = ot.post_id 
                    AND ot.meta_key = '_vtp_outlet_id' 
                    AND ot.meta_value = {$outlet_id}
				INNER JOIN {$this->postmeta} AS oam ON {$this->posts}.ID = oam.post_id 
                    AND oam.meta_key = '_order_total'
				WHERE {$this->posts}.post_date_gmt BETWEEN '{$start_time}' AND '{$end_time}'
                    AND {$this->posts}.post_type = 'shop_order'
                    AND {$this->posts}.post_status = '{$status}'
				ORDER BY order_amount DESC
				LIMIT {$limit}";
		}

		return ViteposModel::get_db_object()->get_results( $query );
	}

	/**
	 * The rate wise tax total is generated by appsbd
	 *
	 * @param mixed $outlet_id It is outlet_id param.
	 * @param mixed $start_time It is start_time param.
	 * @param mixed $end_time It is end_time param.
	 */
	public function rate_wise_tax_total($outlet_id, $start_time, $end_time){
		$start_time = $this->get_full_date( $start_time );
		$end_time   = $this->get_full_date( $end_time, false );
		if($this->is_hpos()){
			$query = "SELECT
    				tl.tax_rate_id,
    				tr.tax_rate_name,
    				SUM(order_tax) as total_tax
				FROM {$this->wc_order_tax_lookup} AS tl
  				INNER JOIN  {$this->wc_orders_meta} AS om on tl.order_id = om.order_id 
  					AND om.meta_key = '_is_vitepos'
  				    AND om.meta_value = 'Y'
  				INNER JOIN {$this->wc_orders_meta} AS ot ON tl.order_id = ot.order_id
  				    AND ot.meta_key = '_vtp_outlet_id'
  				    AND ot.meta_value = {$outlet_id}
  				LEFT JOIN {$this->woocommerce_tax_rates} AS tr ON tl.tax_rate_id = tr.tax_rate_id
 				WHERE tl.date_created BETWEEN '{$start_time}' AND '{$end_time}'
 				GROUP BY tl.tax_rate_id
  				ORDER BY tl.tax_rate_id ASC";
		}else{
			$query = "SELECT
    				tl.tax_rate_id,
    				tr.tax_rate_name,
    				SUM(order_tax) AS total_tax
				FROM {$this->wc_order_tax_lookup} AS tl
  				INNER JOIN {$this->postmeta} AS om ON tl.order_id = om.post_id
  				    AND om.meta_key = '_is_vitepos' 
  				    AND om.meta_value = 'Y'
  				INNER JOIN {$this->postmeta} AS ot ON tl.order_id = ot.post_id
  				    and ot.meta_key = '_vtp_outlet_id'
  				    and ot.meta_value = {$outlet_id}
				LEFT JOIN {$this->woocommerce_tax_rates} AS tr ON tl.tax_rate_id = tr.tax_rate_id
 				WHERE tl.date_created BETWEEN '{$start_time}' AND '{$end_time}'
 				GROUP BY tl.tax_rate_id
  				ORDER BY tl.tax_rate_id ASC";
		}
		return ViteposModel::get_db_object()->get_results( $query );
	}

	/**
	 * The get status is generated by appsbd
	 *
	 * @param mixed $status It is status param.
	 *
	 * @return mixed|string
	 */
	private function get_status( $status = null ) {
		if ( empty( $status ) ) {
			return POS_Settings::def_oder_status();
		} else {
			return $status;
		}
	}
}
