<?php
/**
 * Pos Warehouse Database Model
 *
 * @package Vitepos\Models\Database
 */

namespace Vitepos\Models\Database;

use VitePos\Core\ViteposModel;


/**
 * Class Mapbd_pos_cash_drawer_log
 *
 * @package Vitepos\Models\Database
 */
class Mapbd_Pos_Tips_Log extends ViteposModel {
	/**
	 * Its property id
	 *
	 * @var int
	 */
	public $id;
	/**
	 * Its property cash_drawer_id
	 *
	 * @var string
	 */
	public $cashdrawer_id;
	/**
	 * Its property ref_id
	 *
	 * @var int
	 */
	public $outlet_id;
	/**
	 * Its property ref_id
	 *
	 * @var float
	 */
	public $amount;
	/**
	 * Its property ref_id
	 *
	 * @var float
	 */
	public $prev_amount;
	/**
	 * Its property ref_id
	 *
	 * @var int
	 */
	public $user_to;
	/**
	 * Its property ref_id
	 *
	 * @var int
	 */
	public $user_by;
	/**
	 * Its property ref_id
	 *
	 * @var String
	 */
	public $ref_val;
	/**
	 * Its property note
	 *
	 * @var String
	 */
	public $msg;
	/**
	 * Its property type
	 *
	 * @var String
	 */
	public $type;
	/**
	 * Its property entry_time
	 *
	 * @var String
	 */
	public $entry_date;

	/**
	 * Its property ex param
	 *
	 * @var String
	 */
	public $ex1_param;

	/**
	 * Its property ex2 param
	 *
	 * @var String
	 */
	public $ex2_param;

	/**
	 * Mapbd_pos_cash_drawer_log constructor.
	 */
	public function __construct() {
		parent::__construct();
		$this->SetValidation();
		$this->table_name     = 'apbd_pos_tips_log';
		$this->primary_key    = 'id';
		$this->unique_key     = array();
		$this->multi_key      = array();
		$this->auto_inc_field = array( 'id' );
		$this->app_base_name  = 'apbd-vite-pos';
	}


	/**
	 * The set validation is generated by appsbd
	 */
	public function set_validation() {
		$this->validations = array(
			'id'         => array(
				'Text' => 'Id',
				'Rule' => 'max_length[10]|integer',
			),
			'cashdrawer_id' => array(
				'Text' => 'Cashdrawer Id',
				'Rule' => 'max_length[11]|integer',
			),
			'outlet_id'  => array(
				'Text' => 'Outlet Id',
				'Rule' => 'max_length[50]',
			),
			'amount'  => array(
				'Text' => 'Amount',
				'Rule' => 'max_length[8]|decimal',
			),
			'prev_amount'  => array(
				'Text' => 'Amount',
				'Rule' => 'max_length[8]|decimal',
			),
			'user_to'    => array(
				'Text' => 'User To',
				'Rule' => 'max_length[11]',
			),
			'user_by'    => array(
				'Text' => 'User To',
				'Rule' => 'max_length[11]',
			),
			'msg'        => array(
				'Text' => 'Note',
				'Rule' => 'max_length[255]',
			),
			'ref_val'    => array(
				'Text' => 'Ref Val',
				'Rule' => 'max_length[100]',
			),
			'type'       => array(
				'Text' => 'Log Type',
				'Rule' => 'max_length[1]',
			),
			'entry_date' => array(
				'Text' => 'Entry Time',
				'Rule' => 'max_length[20]',
			),

		);
	}

	/**
	 * The get property raw options is generated by appsbd
	 *
	 * @param mixed   $property Its the property.
	 * @param boolean $is_with_select False if with select.
	 *
	 * @return array|string[]
	 */
	public function get_property_raw_options( $property, $is_with_select = false ) {
		$return_obj = array();
		switch ( $property ) {
			case 'type':
				$return_obj = array(
					'O' => 'Order',
					'W' => 'Withdraw',
				);
				break;
			default:
		}
		if ( $is_with_select ) {
			return array_merge( array( '' => 'Select' ), $return_obj );
		}
		return $return_obj;
	}

	/**
	 * The AddLog is generated by appsbd
	 *
	 * @param mixed  $type Its type param.
	 * @param mixed  $outlet_id Its outlet_id param.
	 * @param mixed  $cashdrawer_id Its product_id param.
	 * @param mixed  $pre_amount Its pre_stock param.
	 * @param mixed  $amount Its stock_val param.
	 * @param mixed  $msg Its msg param.
	 * @param string $ref_val Its ref_val param.
	 * @param string $ref_type Its ref_type param.
	 * @param string $stock_type Its stock_type param.
	 * @param string $ex1_param Its ex1_param param.
	 * @param string $ex2_param Its ex2_param param.
	 *
	 * @return bool
	 */
	public static function AddLog( $type, $outlet_id, $cashdrawer_id, $pre_amount, $amount, $user_to, $user_by, $ref_val = '', $msg = '', $ex1_param = '', $ex2_param = '' ) {
		$check = new self();
		if ( $check->is_exists(
			'ref_val',
			$ref_val,
			array(
				'type' => $type,
				'cashdrawer_id' => $cashdrawer_id,
				'prev_amount' => $pre_amount,
			)
		) ) {
			return;
		}
		$newobj = new self();
		$newobj->cashdrawer_id( $cashdrawer_id );
		$newobj->outlet_id( $outlet_id );
		$newobj->user_to( $user_to );
		$newobj->user_by( $user_by );
		$newobj->amount( $amount );
		$newobj->prev_amount( $pre_amount );
		$newobj->msg( $msg );
		$newobj->ref_val( $ref_val );
		$newobj->type( $type );
		$newobj->entry_date(  gmdate( 'Y-m-d H:i:s' ) );
		$newobj->ex1_param( $ex1_param );
		$newobj->ex2_param( $ex2_param );
		return $newobj->save();
	}
	public static function total_tips_by_cash_drawer( $cashdrawer_id ) {
		$db                      = self::get_db_object();
		$prefix                  = $db->prefix;
		$query                   = "SELECT 	type,SUM(amount) as total
			FROM {$prefix}apbd_pos_tips_log
			WHERE cashdrawer_id =$cashdrawer_id
			GROUP BY type";
		$this_obj                = new self();
		$results                 = $this_obj->select_query( $query );
		foreach ( $results as &$result ) {
			if ( $result->type == 'O' ) {
				$result->title = 'Tips';
			} else {
				$result->title = 'Withdrawn Tips';
			}
		}
		return $results;
	}



	/**
	 * The create db table is generated by appsbd
	 */
	public static function create_db_table() {
		$this_obj = new static();
		$table    = $this_obj->db->prefix . $this_obj->table_name;
		if ( $this_obj->db->get_var( "show tables like '{$table}'" ) != $table ) {
			$sql = "CREATE TABLE `{$table}` (
					`id` int unsigned NOT NULL AUTO_INCREMENT,
                    `cashdrawer_id` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'It is Either will be drawer id or Online',
                    `outlet_id` int unsigned NOT NULL,
                    `user_to` int unsigned NOT NULL,
                    `user_by` int unsigned NOT NULL,
                    `ref_val` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
                    `type` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'radio(O=Order,W=Withdraw)',
                    `entry_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    `msg` char(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
                    `prev_amount` decimal(8,2) NOT NULL DEFAULT '0.00',
                    `amount` decimal(8,2) unsigned NOT NULL DEFAULT '0.00',
  					`ex1_param` char(64) NOT NULL DEFAULT '' COMMENT 'extra fields',
  					`ex2_param` char(64) NOT NULL DEFAULT '' COMMENT 'extra fields',  					
  					PRIMARY KEY (`id`)
					)";
			require_once ABSPATH . 'wp-admin/includes/upgrade.php';
			dbDelta( $sql );
		}
	}
}
