<?php
/**
 * Its api for report
 *
 * @since: 12/07/2021
 * @author: Sarwar Hasan
 * @version 1.0.0
 * @package VitePos\Api\V1
 */

namespace VitePos\Api\V1;

use Appsbd\V1\libs\API_Data_Response;
use Automattic\WooCommerce\Utilities\OrderUtil;
use VitePos\Core\ViteposModel;
use VitePos\Libs\API_Base;
use VitePos\Libs\POS_Order;
use VitePos\Libs\POS_Product;
use VitePos\Libs\Vitepos_Report_Data;
use Vitepos\Models\Database\Mapbd_Pos_Warehouse;
use VitePos\Modules\POS_Settings;

/**
 * Class Pos_Report_Api
 *
 * @package VitePos\Api\V1
 */
class Pos_Report_Api extends API_Base {
	/**
	 * The   get is generated by appsbd
	 *
	 * @param mixed $name It is n param.
	 *
	 * @return string
	 */
	public function __get( $name ) {
		global $wpdb;

		return $wpdb->prefix . $name;
	}

	/**
	 * The is hpos is generated by appsbd
	 *
	 * @return bool
	 */
	public function is_hpos() {
		return OrderUtil::custom_orders_table_usage_is_enabled();
	}

	/**
	 * The set api base is generated by appsbd
	 *
	 * @return mixed|string
	 */
	public function set_api_base() {
		return 'report';
	}


	/**
	 * The routes is generated by appsbd
	 *
	 * @return mixed|void
	 */
	public function routes() {
		$this->register_rest_route( 'POST', 'order-report', array( $this, 'order_report' ) );
		$this->register_rest_route( 'POST', 'product-report', array( $this, 'product_report' ) );
		$this->register_rest_route( 'POST', 'product-report-download', array( $this, 'product_report_download' ) );
		$this->register_rest_route( 'POST', 'product-info', array( $this, 'product_info' ) );
		$this->register_rest_route( 'POST', 'product-details-report', array( $this, 'product_details' ) );
		$this->register_rest_route( 'POST', 'customer-report', array( $this, 'customer_report' ) );
		$this->register_rest_route( 'POST', 'staff-report', array( $this, 'staff_report' ) );
		$this->register_rest_route( 'POST', 'dashboard-report', array( $this, 'dashboard_report' ) );
	}

	/**
	 * The set route permission is generated by appsbd
	 *
	 * @param \VitePos\Libs\any $route Its string.
	 *
	 * @return bool|void
	 */
	public function set_route_permission( $route ) {
		if ( "dashboard-report == $route" ) {
			return current_user_can( 'report-menu' );
		} elseif ( "order-report == $route" ) {
			return current_user_can( 'report-order' );
		} elseif ( 'product-report' == $route ) {
			return current_user_can( 'report-product' );
		} elseif ( 'customer-report' == $route ) {
			return current_user_can( 'report-customer' );
		} else {
			return current_user_can( 'report-staff' );
		}

		return parent::set_route_permission( $route );
	}

	/**
	 * The order report is generated by appsbd
	 *
	 * @return \Appsbd\V1\libs\API_Response
	 */
	public function order_report() {
		$response_data = new API_Data_Response();
		$args          = array(
			'status'        => array( POS_Settings::def_oder_status(), 'completed' ),
			'limit'         => $this->get_payload( 'limit', 20 ),
			'page'          => $this->get_payload( 'page', 1 ),
			'orderby'       => 'date',
			'order'         => 'DESC',
			'paginate'      => true,
			'vt_meta_query' => array(
				array(
					'key'     => '_is_vitepos',
					'value'   => 'Y',
					'compare' => '=',
				),
			),
		);
		if ( ! POS_Settings::is_admin_user() && ! current_user_can( 'can-refund-any-order' ) ) {
			$outlets = get_user_meta( $this->get_current_user_id(), 'outlet_id', true );
			if ( is_array( $outlets ) ) {
				$args['vt_meta_query'][] = array(
					'key'     => '_vtp_outlet_id',
					'value'   => $outlets,
					'compare' => 'IN',
				);
			} else {
				$this->add_error( "You don't have permission to view details of this outlet" );
				$response_data->set_total_records( 0 );
				$this->response->set_response( false, '', $response_data );

				return $this->response->get_response();
			}
		}
		$src_props     = $this->get_payload( 'src_by', array() );
		$sort_by_props = $this->get_payload( 'sort_by', array() );
		POS_Order::order_search_props( $args, $src_props );
		POS_Order::order_sort_param( $sort_by_props, $args );

		$orders = wc_get_orders( $args );

		$orderlist = array();
		if ( ! empty( $orders->orders ) && is_array( $orders->orders ) ) {
			foreach ( $orders->orders as $order ) {
				$order_data  = POS_Order::get_from_woo_order( $order );
				$orderlist[] = $order_data;
			}
		}

		$page                 = $this->get_payload( 'page', 1 );
		$limit                = $this->get_payload( 'limit', 20 );
		$response_data->page  = $page;
		$response_data->limit = $limit;
		$type                 = $this->get_payload( 'request_type', '' );
		if ( ! empty( $type ) && 'pdf' == $type ) {
			if ( ! empty( $orders->total ) ) {
				$limit                = $this->set_limit( $orders->total );
				$response_data->limit = $limit;
			}
		}

		if ( $response_data->set_total_records( $orders->total ) ) {
			$response_data->rowdata = $orderlist;
		}

		$this->response->set_response( true, 'Order found', $response_data );

		return $this->response;
	}

	/**
	 * The product report is generated by appsbd
	 *
	 * @return API_Data_Response
	 */
	public function product_report() {
		$response_data = new API_Data_Response();
		$report        = new Vitepos_Report_Data();
		$src_props     = $this->get_payload( 'src_by', array() );
		$sort_by_props = $this->get_payload( 'sort_by', array() );

		$start_date = null;
		$end_date   = null;
		$outlet_id  = null;
		foreach ( $src_props as $item ) {
			if ( isset( $item['prop'] ) && 'outlet_id' === $item['prop'] ) {
				$outlet_id = $item['val'];
			}
			if ( isset( $item['prop'] ) && 'order_date' === $item['prop'] ) {
				if ( is_array( $item['val'] ) ) {
					$start_date = $item['val']['start'];
					$end_date   = $item['val']['end'];
				} else {
					$start_date = $item['val'];
					$end_date   = $item['val'];
				}
			}
		}
		if ( empty( $outlet_id ) ) {
			$outlet_id = $this->get_outlet_id();
		}

		if ( $this->is_hpos() ) {
			$total_product = ViteposModel::get_db_object()->get_results(
				"
		SELECT COUNT(*) AS total_records
		FROM (
    		SELECT 
        		{$this->posts}.ID AS counted_product_id,
        		{$this->posts}.post_type
    		FROM {$this->posts}
   			WHERE {$this->posts}.post_type IN ('product', 'product_variation') 
      			AND {$this->posts}.post_status IN  ('publish','private')
    		GROUP BY 
        		{$this->posts}.ID
			) AS product_counts
		WHERE 
    		(post_type = 'product' 
    			AND NOT EXISTS (
        		SELECT 1 
        			FROM {$this->posts} AS variations 
       				WHERE variations.post_parent = product_counts.counted_product_id 
        				AND variations.post_type = 'product_variation'
    			)
    		) 
    	OR post_type = 'product_variation';
		"
			);
		} else {
			$total_product = ViteposModel::get_db_object()->get_results(
				"
			SELECT COUNT(*) AS total_records
			FROM (
                SELECT 
                    {$this->posts}.ID AS counted_product_id,
                    {$this->posts}.post_type
                FROM {$this->posts}
                LEFT JOIN {$this->posts} AS variations ON variations.post_parent = {$this->posts}.ID 
                    AND variations.post_type = 'product_variation'
                WHERE {$this->posts}.post_type IN ('product', 'product_variation') 
                    AND {$this->posts}.post_status IN  ('publish','private')
                GROUP BY {$this->posts}.ID
                HAVING ({$this->posts}.post_type = 'product' AND COUNT(variations.ID) = 0)
                    OR {$this->posts}.post_type = 'product_variation'
			) AS product_counts;"
			);
		}

		$page                 = $this->get_payload( 'page', 1 );
		$limit                = $this->get_payload( 'limit', 20 );
		$response_data->page  = $page;
		$response_data->limit = $limit;

		$product_list = $report->product_list( $outlet_id, $start_date, $end_date, $limit, $page );
		foreach ( $product_list as &$product ) {
			if ( ! empty( $product->product_id ) ) {
				$product->image_url = $this->get_product_img_url( $product->product_id, 'full' );
			}
		}
		if ( $response_data->set_total_records( $total_product[0]->total_records ) ) {
			$response_data->rowdata = $product_list;
		}

		return $response_data;
	}

	/**
	 * The product report download is generated by appsbd
	 */
	public function product_report_download() {
		$response_data = new API_Data_Response();
		$report        = new Vitepos_Report_Data();
		$src_props     = $this->get_payload( 'src_by', array() );
		$sort_by_props = $this->get_payload( 'sort_by', array() );
		$page          = $this->get_payload( 'page', 1 );
		$limit         = $this->get_payload( 'limit', 20 );

		$start_date = null;
		$end_date   = null;
		$outlet_id  = null;
		foreach ( $src_props as $item ) {
			if ( isset( $item['prop'] ) && 'outlet_id' === $item['prop'] ) {
				$outlet_id = $item['val'];
			}
			if ( isset( $item['prop'] ) && 'order_date' === $item['prop'] ) {
				if ( is_array( $item['val'] ) ) {
					$start_date = $item['val']['start'];
					$end_date   = $item['val']['end'];
				} else {
					$start_date = $item['val'];
					$end_date   = $item['val'];
				}
			}
		}
		if ( empty( $outlet_id ) ) {
			$outlet_id = $this->get_outlet_id();
		}
		$product_list = $report->product_list( $outlet_id, $start_date, $end_date, $limit, $page );
		foreach ( $product_list as &$product ) {
			if ( ! empty( $product->product_id ) ) {
				$product->image_url = $this->get_product_img_url( $product->product_id, 'full' );
			}
		}
		$response_data->page  = $page;
		$response_data->limit = $limit;

		if ( $response_data->set_total_records( 100 ) ) {
			$response_data->rowdata = $product_list;
		}

		return $response_data;
	}

	/**
	 * The scan product is generated by appsbd
	 *
	 * @return \Appsbd\V1\libs\API_Response
	 */
	public function product_details() {
		$report     = new Vitepos_Report_Data();
		$product_id = $this->get_payload( 'id', '' );
		$stock_type = POS_Settings::is_default_stock() ? '_stock' : '_vt_stocks';
		if ( ! empty( $product_id ) ) {
			$product_info               = new \stdClass();
			$product_info->product_data = $report->search_product( $product_id );
			$product_info->img_url      = $this->get_product_img_url( $product_id, 'full' );
			$product_stock              = ViteposModel::get_db_object()->get_results( "SELECT meta_value as stock FROM {$this->postmeta} WHERE {$this->postmeta}.post_id = {$product_id} AND {$this->postmeta}.meta_key = '{$stock_type}';" );

			if ( POS_Settings::is_default_stock() ) {
				$product_info->stock_data = $product_stock ? appsbd_wc_amount( $product_stock[0]->stock ) : 0;
			} elseif ( ! empty( $product_stock ) && isset( $product_stock[0]->stock ) ) {
				$product_info->stock_data = unserialize( $product_stock[0]->stock );
			} else {
				$product_info->stock_data = array();
			}
			$outlets       = Mapbd_pos_warehouse::get_outlet_details( null, true );
			$product_assoc = array();
			foreach ( $product_info->product_data as $product ) {
				$product_assoc[ $product->outlet_id ] = $product;
			}
			foreach ( $outlets as $outlet ) {
				if ( ! isset( $product_assoc[ $outlet->id ] ) ) {
					$product_assoc[ $outlet->id ] = array(
						'outlet_id'         => $outlet->id,
						'total_ordered_qty' => 0,
					);
				}
			}
			$product_info->product_data = $product_assoc;
			if ( ! empty( $product_info ) ) {
				$this->response->set_response( true, 'Product found', $product_info );
			} else {
				$this->response->set_response( false, 'No product Found', array() );
			}

			return $this->response;
		} else {
			$this->response->set_response( false, 'Invalid Id', array() );
		}

		return $this->response;
	}


	/**
	 * The product info is generated by appsbd
	 *
	 * @return \Appsbd\V1\libs\API_Response
	 */
	public function product_info() {
		self::set_vite_pos_request();
		$page                = $this->get_payload( 'page', 1 );
		$limit               = $this->get_payload( 'limit', 20 );
		$src_props           = $this->get_payload( 'src_by', array() );
		$sort_by_props       = $this->get_payload( 'sort_by', array() );
		$response_product    = POS_Product::get_product_from_woo_products_without_variables(
			$page,
			$limit,
			$src_props,
			$sort_by_props
		);
		$response_data       = new API_Data_Response();
		$response_data->page = $page;

		if ( $response_data->set_total_records( $response_product->records ) ) {
			$response_data->rowdata = $response_product->products;
		}
		$this->response->set_response( true, '', $response_data );

		return $this->response;
	}

	/**
	 * The customer report is generated by appsbd
	 */
	public function customer_report() {
		$response_data = new API_Data_Response();
		$report        = new Vitepos_Report_Data();

		$src_props     = $this->get_payload( 'src_by', array() );
		$sort_by_props = $this->get_payload( 'sort_by', array() );

		$outlet_id       = null;
		$name            = null;
		$email           = null;
		$name_condition  = '';
		$email_condition = '';

		foreach ( $src_props as $item ) {
			if ( isset( $item['prop'] ) && 'outlet_id' === $item['prop'] ) {
				$outlet_id = $item['val'];
			}
			if ( isset( $item['prop'] ) && 'name' === $item['prop'] ) {
				$name           = trim( $item['val'], " \n\r\t\v\0" );
				$name_condition = "AND ({$this->users}.display_name LIKE '$name' OR {$this->users}.user_login LIKE '$name' OR fn.meta_value LIKE '$name' OR ln.meta_value Like '$name')";
			}
			if ( isset( $item['prop'] ) && 'email' === $item['prop'] ) {
				$email           = trim( $item['val'], " \n\r\t\v\0" );
				$email_condition = "AND {$this->users}.user_email = '$email'";
			}
		}

		if ( empty( $outlet_id ) ) {
			$outlet_id = $this->get_outlet_id();
		}
		if ( $this->is_hpos() ) {
			$total_customer = ViteposModel::get_db_object()->get_results(
				"
			SELECT
				COUNT(DISTINCT {$this->users}.ID) AS user_count 
				FROM {$this->wc_orders}
				INNER JOIN {$this->users} ON {$this->wc_orders}.customer_id = {$this->users}.ID 	
				INNER JOIN {$this->wc_orders_meta} AS ot ON {$this->wc_orders}.id = ot.order_id 
					AND ot.meta_key = '_vtp_outlet_id' 
					AND ot.meta_value = {$outlet_id}
				LEFT JOIN {$this->usermeta} AS fn ON {$this->users}.ID = fn.user_id 
                     AND fn.meta_key = 'first_name'
                LEFT JOIN {$this->usermeta} AS ln ON {$this->users}.ID = ln.user_id 
                    AND ln.meta_key = 'last_name'	
	
				WHERE 1=1
				{$name_condition}
				{$email_condition}"
			);
		} else {
			$total_customer = ViteposModel::get_db_object()->get_results(
				"
			SELECT
                COUNT(DISTINCT u.id) AS user_count
				FROM {$this->posts}
				INNER JOIN {$this->postmeta} AS ot ON {$this->posts}.ID = ot.post_id 
                    AND ot.meta_key = '_vtp_outlet_id' 
                    AND ot.meta_value = {$outlet_id}
				INNER JOIN {$this->postmeta} AS um ON {$this->posts}.ID = um.post_id 
                    AND um.meta_key = '_customer_user'
				INNER JOIN {$this->users} AS u ON um.meta_value = u.ID
				LEFT JOIN {$this->usermeta} AS fn ON u.ID = fn.user_id 
                    AND fn.meta_key = 'first_name'
                LEFT JOIN {$this->usermeta} AS ln ON u.ID = ln.user_id 
                    AND ln.meta_key = 'last_name'
				WHERE 1=1
				{$name_condition}
				{$email_condition}"
			);
		}

		$page                 = $this->get_payload( 'page', 1 );
		$limit                = $this->get_payload( 'limit', 20 );
		$response_data->page  = $page;
		$response_data->limit = $limit;
		$type                 = $this->get_payload( 'request_type', '' );
		if ( ! empty( $type ) && 'pdf' == $type ) {
			if ( ! empty( $total_customer[0]->user_count ) ) {
				$limit                = $this->set_limit( $total_customer[0]->user_count );
				$response_data->limit = $limit;
			}
		}

		$customer_data = $report->top_customers( $outlet_id, null, null, $name, $email, $limit, $page );

		if ( $response_data->set_total_records( $total_customer[0]->user_count ) ) {
			$response_data->rowdata = $customer_data;
		}

		return $response_data;
	}

	/**
	 * The staff report is generated by appsbd
	 */
	public function staff_report() {
		$response_data = new API_Data_Response();
		$report        = new Vitepos_Report_Data();
		$src_props     = $this->get_payload( 'src_by', array() );
		$sort_by_props = $this->get_payload( 'sort_by', array() );

		$outlet_id       = null;
		$start_date      = null;
		$end_date        = null;
		$user_id         = null;
		$email           = null;
		$email_condition = '';
		$id_condition    = '';

		foreach ( $src_props as $item ) {
			if ( isset( $item['prop'] ) && 'outlet_id' === $item['prop'] ) {
				$outlet_id = $item['val'];
			}
			if ( isset( $item['prop'] ) && 'order_date' === $item['prop'] ) {
				if ( is_array( $item['val'] ) ) {
					$start_date = $item['val']['start'];
					$end_date   = $item['val']['end'];
				} else {
					$start_date = $item['val'];
					$end_date   = $item['val'];
				}
			}
			if ( isset( $item['prop'] ) && 'user_id' === $item['prop'] ) {
				$user_id      = trim( $item['val'], " \n\r\t\v\0" );
				$id_condition = "AND {$this->users}.ID = '$user_id'";
			}
			if ( isset( $item['prop'] ) && 'email' === $item['prop'] ) {
				$email           = trim( $item['val'], " \n\r\t\v\0" );
				$email_condition = "AND {$this->users}.user_email = '$email'";
			}
		}

		if ( empty( $outlet_id ) ) {
			$outlet_id = $this->get_outlet_id();
		}
		if ( $this->is_hpos() ) {
			$staff_count = ViteposModel::get_db_object()->get_results(
				"
			SELECT
                COUNT(DISTINCT um.meta_value) AS user_count
				FROM {$this->wc_orders} AS orders
				INNER JOIN {$this->wc_orders_meta} AS ot ON orders.id = ot.order_id
                    AND ot.meta_key = '_vtp_outlet_id'
                    AND ot.meta_value = {$outlet_id}
				INNER JOIN {$this->wc_orders_meta} AS um ON orders.id = um.order_id
                    AND um.meta_key = '_vtp_processed_by'
				INNER JOIN {$this->users} ON um.meta_value = {$this->users}.ID
				WHERE 1=1
				{$id_condition}
				{$email_condition}"
			);
		} else {
			$staff_count = ViteposModel::get_db_object()->get_results(
				"
				SELECT
					COUNT( DISTINCT um.meta_value ) AS user_count
					FROM {$this->posts}
					INNER JOIN {$this->postmeta} AS ot ON {$this->posts}.id = ot.post_id 
						AND ot.meta_key = '_vtp_outlet_id' 
						AND ot.meta_value = {$outlet_id}
					INNER JOIN {$this->postmeta} AS um ON {$this->posts}.id = um.post_id 
						AND um.meta_key = '_vtp_processed_by'
					INNER JOIN {$this->users} ON um.meta_value = {$this->users}.ID 
					WHERE 1=1
					{$id_condition}
					{$email_condition}"
			);
		}

		$page                 = $this->get_payload( 'page', 1 );
		$limit                = $this->get_payload( 'limit', 20 );
		$response_data->page  = $page;
		$response_data->limit = $limit;
		$type                 = $this->get_payload( 'request_type', '' );
		if ( ! empty( $type ) && 'pdf' == $type ) {
			if ( ! empty( $staff_count[0]->user_count ) ) {
				$limit                = $this->set_limit( $staff_count[0]->user_count );
				$response_data->limit = $limit;
			}
		}

		$staff_data = $report->top_staffs( $outlet_id, $start_date, $end_date, $limit, $page, $user_id, $email );
		if ( $response_data->set_total_records( $staff_count[0]->user_count ) ) {
			$response_data->rowdata = $staff_data;
		}

		return $response_data;
	}

	/**
	 * The dashboard report is generated by appsbd
	 */
	public function dashboard_report() {
		$report        = new Vitepos_Report_Data();
		$src_props     = $this->get_payload( 'src_by', array() );
		$sort_by_props = $this->get_payload( 'sort_by', array() );

		$start_date = null;
		$end_date   = null;
		$outlet_id  = null;
		foreach ( $src_props as $item ) {
			if ( isset( $item['prop'] ) && 'outlet_id' === $item['prop'] ) {
				$outlet_id = $item['val'];
			}
			if ( isset( $item['prop'] ) && 'order_date' === $item['prop'] ) {
				if ( is_array( $item['val'] ) ) {
					$start_date = $item['val']['start'];
					$end_date   = $item['val']['end'];
				} else {
					$start_date = $item['val'];
					$end_date   = $item['val'];
				}
			}
		}
		if ( empty( $outlet_id ) ) {
			$outlet_id = $this->get_outlet_id();
		}
		
		$order_data = $report->day_wise_order( $outlet_id, $start_date, $end_date );

		
		$top_orders = $report->top_orders( $outlet_id, $start_date, $end_date, 'wc-completed' );

		
		$top_refunds = $report->top_orders( $outlet_id, $start_date, $end_date, 'wc-refunded' );

		
		$payment_method_data = $report->payment_methods_report( $outlet_id, $start_date, $end_date );

		
		$product_data = $report->top_products( $outlet_id, $start_date, $end_date );
		foreach ( $product_data as &$product ) {
			if ( ! empty( $product->ID ) ) {
				$product->product_img = $this->get_product_img_url( $product->ID, 'full' );
			}
		}

		
		$customer_data = $report->top_customers( $outlet_id, $start_date, $end_date );
		foreach ( $customer_data as &$customer ) {
			if ( $customer->user_email ) {
				$customer->customer_img = $this->get_gravatar_url( $customer->user_email, 'full' );
			} else {
				$customer->customer_img = $this->get_gravatar_url( null );
			}
		}

		
		$staff_data = $report->top_staffs( $outlet_id, $start_date, $end_date );
		foreach ( $staff_data as &$staff ) {
			if ( $staff->user_email ) {
				$staff->staff_img = $this->get_gravatar_url( $staff->user_email, 'full' );
			} else {
				$staff->staff_img = $this->get_gravatar_url( null );
			}
		}

		$response_data = array(
			'order_data'           => $order_data,
			'payment_method_data'  => $payment_method_data,
			'product_data'         => $product_data,
			'staff_data'           => $staff_data,
			'customer_data'        => $customer_data,
			'top_orders'           => $top_orders,
			'top_refunds'          => $top_refunds,
		);

		
		$tax_display_totals = get_option( 'woocommerce_tax_total_display', 'single' );
		if ( 'itemized' === $tax_display_totals ) {
			$rate_wise_tax_totals = $report->rate_wise_tax_total($outlet_id,$start_date,$end_date);
			$response_data['rate_wise_tax_totals'] = $rate_wise_tax_totals;
		}

		$this->response->set_response( true, '', $response_data );

		return $this->response;
	}

	/**
	 * The get gravatar url is generated by appsbd
	 *
	 * @param mixed $email It is email param.
	 * @param int $size It is size param.
	 *
	 * @return string
	 */
	public function get_gravatar_url( $email, $size = 50 ) {
		if ( $email ) {
			$grav_url = 'https://www.gravatar.com/avatar/' . md5( strtolower( trim( $email ) ) ) . '?s=' . $size;
		} else {
			$grav_url = 'https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y';
		}

		return $grav_url;
	}

	/**
	 * The get product img url is generated by appsbd
	 *
	 * @param mixed $id It is i param.
	 * @param mixed $size It is s param.
	 */
	public function get_product_img_url( $id, $size = 50 ) {
		$product = wc_get_product( $id );
		if ( ! $product ) {
			return false;
		}
		$image_id = $product->get_image_id();
		if ( ! empty( $image_id ) ) {
			return wp_get_attachment_image_url( $image_id, $size );
		} else {
			return false;
		}
	}

	/**
	 * The set limit is generated by appsbd
	 *
	 * @param float|int $data It is data param.
	 *
	 * @return float|int
	 */
	public function set_limit( $data ) {
		$ceil_data = ceil( $data / 50 );

		return ( 50 * $ceil_data ) / 5;
	}
}
